elixir-lang/elixir-lang.github.com

css/style.css, css/syntax.css
* simplify colors in syntax.css
* remove unused column classes in style.css
* clean format styles.css  to be consistent (more than one declaration per line, is split into multiple lines)
=> clean css files

css/style.css
This fixes the issue with the size of the title mentioned in #403
=> fix entry title font size in /blog/

getting_started/mix_otp/5.markdown
=> Small typo fix

css/style.css
convert to lowercase all HEX colors
=> standardize color to lowercase

getting_started/19.markdown
- Rephrased some sentences (mainly to fix inconsistent addressing: "to do
that, YOU can do this [...] and so WE need to ...")
- Polished some of the code samples
Some of the changes are explained through comments in the diff. If you need me to change anything just let me know :+1:.
=> Rephrased some sentences and fixed some grammar in ch. 19

getting_started/20.markdown
Too many i-s and y-s here... ^^
=> Spelling: Dyalizer => Dialyzer

getting_started/19.markdown
Just rephrased some sentences and cleaned out here and there.
Most of the changes are justified in the comments throughout the diff.
=> Minor rephrasing and refactorings to the try/catch chapter

getting_started/15.markdown
- Updated some code samples to be more explanatory
- Updated some code samples to bring them up to date with Elixir 1.0
- Rephrased some sentences here and there
- Moved some stuff around so that the chapter flows more naturally
- Added section titles so that the chapter is more structured
As usual, most changes are justified in the comments throughout the diff :smiley:.
=> Update prose and code in the chapter about structs

getting_started/9.markdown
- Minor fixes here and there
- Rephrased a couple of sentences
=> Polish stuff in the chapter about recursion (ch. 9)

getting_started/13.markdown
- Fixed some minor grammar errors
- Rephrased a couple of sentences
- Added a note at the very end of the chapter (about module nesting)
As usual, most changes are justified in the diff's comments.
=> Very small polishes in chapter 13

getting_started/20.markdown
=> Fix a couple of typos in chapter 20

getting_started/21.markdown
Mostly very minor rephrasings here and there.
=> Minor fixes to chapter 21 of the Getting Started guide

_includes/learning-resources.html, install.markdown
* New "Metaprogramming Elixir" book added
* Link's titles now contain: Book Title: Subtitle: Author
* Update Programming Elixir link to avoid redirect
* Minor Fix install.html, as it wasn't validating
=> Learning resources updated

getting_started/18.markdown
I was going through the tutorial and noticed this error.
=> Update example in Sigils chapter to corretly return negative integer

getting_started/meta/2.markdown
- Minor whitespace fixes
- Minor content edits
Most of the "relevant" changes are explained through comments in the commit's diff. Thanks!
=> Polish very slightly the second chapter on macros

getting_started/meta/2.markdown
=> fix macro receive

crash-course.markdown
=> highlight as erlang shell (crash-course)

getting-started/mix-otp/genserver.markdown, getting-started/processes.markdown
indentation and correction of style
=> Getting started : corrections

getting-started/mix-otp/genevent.markdown, getting-started/mix-otp/supervisor-and-application.markdown
* Fix GenEven test (fixes #459 )
* Correction in Supervisor runing `iex` with _run_ option (José, could you check this is correct, otherwise it needs rephrasing as it is not clear)
=> Fix GenEven test

install.markdown
=> install.markdown : permanent solution for PATH env. var

css/style.css, getting-started/meta/quote-and-unquote.markdown, learning.markdown
converted dimensions to em from px
add border to book cover
stylized the boooks' anchor title
+bonus:  small correction for getting-started/meta/quote-and-unquote.markdown
=> Improvents in learning resources

_includes/bottom.html, css/style.css
=> bring back numbers to TOC

_includes/index-redirect.html, _includes/top.html, _posts/2014-06-17-elixir-v0-14-0-released.markdown, blog/categories.html, install.markdown
I have been working with [html-proofer](https://github.com/gjtorikian/html-proofer) a nice app that does a lot of checking for your static file website, It found a few internal broken links.
Also this commit adds favicon.ico  explicitly
=> favicon link + Fix broken links

crash-course.markdown
=> correct multiline regex

getting-started/mix-otp/genserver.markdown
In a recent discussion in irc, someone new to Elixir was confused on this point. I wanted to make this what was going on a bit more explicit.
=> Make explicit that client/server are 2 processes

getting-started/case-cond-and-if.markdown
=> add is_nil to list of guard functions + additional message

_data/getting-started.yml, _posts/2014-04-21-elixir-v0-13-0-released.markdown, getting-started/basic-operators.markdown, getting-started/meta/macros.markdown, getting-started/mix-otp/distributed-tasks-and-configuration.markdown, getting-started/modules.markdown, getting-started/protocols.markdown, getting-started/structs.markdown
=> Struct page renamed, and linking to previous chapters

getting-started/case-cond-and-if.markdown
as per @ericmj 's suggestion
https://github.com/elixir-lang/elixir-lang.github.com/pull/501/files#r27769345
=> re-phrase sentence about user defined guard functions

learning.markdown
Added the Elixir Cookbook to the learning section of the website.
=> Added Elixir Cookbook to Learning.

getting-started/mix-otp/task-and-gen-tcp.markdown
The example as it is currently designed will cause all connections to be
dropped if the acceptor crashes because, by default, ports (as returned
by `:gen_tcp.accept/1`) are tied to the process that created them. See
the Erlang docs:
* http://www.erlang.org/doc/reference_manual/ports.html
* http://www.erlang.org/doc/man/gen_tcp.html
Thanks to @tsloughter for helping me confirm it.
=> Change controlling process in the gen_tcp tutorial

getting-started/mix-otp/genevent.markdown
assert_receive timeout is 100ms and not 500ms
See lib/ex_unit/lib/ex_unit/assertions.ex for confirmation
=> Fix assert_receive timeout

getting-started/mix-otp/supervisor-and-application.markdown
I tried to rearrange the narration so that it exposes the same features
while being consistent with the current implementation.
Fix #466
=> Update section on starting applications

getting-started/mix-otp/genserver.markdown
=> Change 'seperate' to 'separate' in mix-otp/genserver

getting-started/mix-otp/ets.markdown, getting-started/recursion.markdown, getting-started/structs.markdown
Hi, thanks for these great guides! I haven't quite finished them but I thought I'd offer a few typo fixes, what do you think?
=> Text changes

getting-started/mix-otp/agent.markdown, getting-started/mix-otp/genevent.markdown, getting-started/mix-otp/genserver.markdown, getting-started/mix-otp/introduction-to-mix.markdown, getting-started/mix-otp/supervisor-and-application.markdown
Sorry for the size, I didn't want to spam you with 5 PRs...
=> Minor updates and typos fix in the mix and otp guide (part one)

getting-started/mix-otp/dependencies-and-umbrella-apps.markdown, getting-started/mix-otp/distributed-tasks-and-configuration.markdown, getting-started/mix-otp/docs-tests-and-pipelines.markdown, getting-started/mix-otp/ets.markdown, getting-started/mix-otp/task-and-gen-tcp.markdown
Here's part two. That guide is really good!
=> Minor updates and typos fix in mix and otp guide (part two)

getting-started/mix-otp/distributed-tasks-and-configuration.markdown
just corrected the filename in the text from routest_test.exs to router_test.exs
=> slight typo on file name

_includes/elixir-radar.html, _includes/top.html, _layouts/blog.html, _layouts/default.html, _layouts/getting-started.html, css/style.css
This PR adds a link to Elixir Radar to the sidebar. Here's a screenshot:
=> Add a Elixir Radar link to the sidebar

install.markdown
You should not advise people to download packages over insecure connections.
=> Upgraded a few links on the Install page to TLS.

getting-started/processes.markdown
The phrase 'dozens of thousands' caught my eye.  How about this?
=> Fix typo in Processes

getting-started/mix-otp/introduction-to-mix.markdown
Should fix some confusion around how this is done on Windows :)
=> Add Windows-specific instructions for passing MIX_ENV to mix

getting-started/case-cond-and-if.markdown
The previous code block says:
> ** (RuntimeError) undefined function: if/1
=> Fix case-cond-and-if document

_posts/2014-08-07-elixir-v0-15-0-released.markdown, install.markdown
as suggested by @ericmj  in https://github.com/elixir-lang/elixir-lang.github.com/issues/566#issuecomment-121229326
=> provide windows installer via https://

_includes/important-links.html
@josevalim I think this is what you are looking for.
=> Add slack signup form to important links

install.markdown
Corrected typo on recommendation to add Elixir's bin path to PATH environment.
=> Corrected typo

_includes/important-links.html
Favouring the official channels at the top of the list.
Closes https://github.com/elixir-lang/elixir-lang.github.com/issues/587
=> Reorganize sidebar links

getting-started/pattern-matching.markdown
I'm just getting started with Elixir and am reading through the Getting Started guides. The pin operator example in the pattern matching chapter got me confused. I've changed the explanation slightly, changed a variable name, and added a "you can also rewrite this as" piece of code to really drive the point home.
As I was asking about this on Slack, I understood it as soon as I compared it to interpolation. Would interpolation be a good term in this case? The way I see it, you're pretty much interpolating the tuple. I'm not sure if that's technically correct and would actually improve the guide or not.
Open to suggestions. These are some of the best docs I've read to date. Keep it up! <3
=> Improves pin operator explanation and examples

css/style.css
Before/after gifs (sorry for the flickering)
The best way for you to validate the changes should be to just pull the branch and run it in your browser :smile: 
**Before**
**After**
=> Add small css tweaks to make the site a bit more adaptive

getting-started/mix-otp/introduction-to-mix.markdown
=> Add elixir: ~> 1.0 to project comp

getting-started/typespecs-and-behaviours.markdown
Resolves https://github.com/elixir-lang/elixir-lang.github.com/issues/620
=> Update behaviour syntax

getting-started/introduction.markdown
Hopefully made it somewhat more beginner friendly.
* Added disclaimer that terminal commands are for unix
* Updated the terminal commands to create, edit and run an elixir file
=> Clarified some stuff in the intro section

getting-started/mix-otp/agent.markdown
* Explained the arguments of the functions update and get
* Added note that Agents only store state and not logic
=> Added more explanation to agent text

install.markdown
=> docs(install.md) change location for erlang package

install.markdown
The added step is going to install all the necessary tools.
=> Update Ubuntu installation procedure

getting-started/mix-otp/supervisor-and-application.markdown
Please suggest what the correct fix is, if I'm not getting it right.
=> Fix typo: missing preposition

getting-started/mix-otp/supervisor-and-application.markdown
I just started learning elixir.
Hopefully, it's the correct fix.
=> Fix type: arity

getting-started/processes.markdown
fixed 'function stars a new process' to 'function starts a new process' :)
=> fixed typo

learning.markdown
Changed the book reference to the 1.2 book, as the old book is out of print.
=> Changed book to 'Programming Elixir 1.2'

_includes/bottom.html, _layouts/getting-started.html, css/style.css
Follow up of the discussion in #697.
=> Better "Edit on GitHub" link in the Getting Started guide

install.markdown
Moved asdf to an organization. This PR updates the link to the repo.
=> Update link to asdf repo

getting-started/mix-otp/supervisor-and-application.markdown
This seems to be a remnant of b965fdb
=> Remove adding unnecessary module attribute to KV.Supervisor

learning.markdown
Added new languages (French + Greek). I also corrected my bad grammar. 
Updated files:
- /learning.markdown
=> Elixir School: Added new languages

getting-started/basic-types.markdown
This seems like a much clearer description of line breaks in strings to me.
=> Update description of line breaks in strings

getting-started/mix-otp/distributed-tasks-and-configuration.markdown
also an unused variable warning in routing layer code
=> Fix output in distributed tasks section

getting-started/modules.markdown
=> Fix hash link to do/end blocks

getting-started/try-catch-and-rescue.markdown
See https://groups.google.com/forum/#!topic/elixir-lang-core/NWvFwUWo2QQ for what I was confused about.
=> Clarify semantics of `after`.

index.html
"WhatsApp" is the official spelling.
=> Whatsapp -> WhatsApp

getting-started/alias-require-and-import.markdown
This commit changes "With this we are almost finishing our tour about Elixir modules. " to "With this we have almost finished our tour of Elixir modules."
=> Change sentence in alias-require-and-import.markdown to use idiomatic English

getting-started/case-cond-and-if.markdown
- Also add error type(CondClauseError) when raised in `cond` clause
=> Add an example for anonymous function

getting-started/keywords-and-maps.markdown
- Also add one example for `maps` where value can be accessed via list.
=> Show correct o/p in the examples

_posts/2016-06-21-elixir-v1-3-0-released.markdown
It seemed like there was a word missing...
=> Clarify text of the release 1.3 blog post

learning.markdown
Hi guys! I added a reference to Red:4 (http://redfour.io) on the learning page, as suggested by Mr. @josevalim.
Thanks!
=> Added Red:4 Learning reference

getting-started/mix-otp/supervisor-and-application.markdown
Should be the verb "set up" not the noun.
=> setup -> set up

getting-started/mix-otp/supervisor-and-application.markdown
I was reading through this and felt that this section didn't explain sufficiently well how we can know that this change is working. I added some paragraphs to try a first approximation. You'll notice it's written like I don't know Elixir because... well, that.
Am I making sense? Would an addition along these lines be helpful to readers?
=> How do we know this is working?

getting-started/basic-types.markdown
=> fixed non-compiling example

getting-started/alias-require-and-import.markdown
Update for abiding by 1.3 lexicals' returned values:
https://github.com/elixir-lang/elixir/issues/4596
https://github.com/elixir-lang/elixir/pull/4629
=> 1.3 lexicals

getting-started/mix-otp/genserver.markdown
Noticed this while reading the docs for supervisor.
=> Reduce indent offset

getting-started/modules.markdown
Per discussion in https://github.com/elixir-lang/elixir/issues/5073
=> Module#scripted-mode section: try to explain the diffrence between .ex and .exs files in a non-confusion way

getting-started/alias-require-and-import.markdown
Sentence should read as:
At this point, you may be wondering: what exactly is an Elixir alias and how is it represented?
or
At this point, you may be wondering what exactly an Elixir alias is and how it is represented.
=> Revise sentence structure in 'Understanding Aliases'

getting-started/mix-otp/introduction-to-mix.markdown
Fixes #682.
Open to changing the wording and location!
=> Add link to finished `kv_umbrella` repo

getting-started/mix-otp/ets.markdown
There's a typo in the ETS chapter.
=> Fix a typo in ETS chapter

_includes/important-links.html
Add alchemist.vim to editor support list
@whatyouhide this new PR
=> Add alchemist.vim to editor list

getting-started/pattern-matching.markdown
An attempt to simplify and add clarity to the text. (I'm an Elixir newbie, but I took a gamble on changing "the sides can't match" to "the sides can't be matched". Based on what I've understood from Dave Thomas's book (the first few pages), I think my version is clearer. Of course I may be wrong!)
One question, is making a pull request with these small edits a useful thing to do, or should I just do it when I see a more serious error in the text? I want to be seen as helpful rather than pedantic to the Elixir community. :-)
=> Three small edits to add clarity and conciseness

install.markdown
This installation procedure works for ubuntu 16.04
=> Update installation instructions for latest ubuntu version

getting-started/protocols.markdown
Following the lead of https://github.com/elixir-lang/elixir/commit/ff9d41c7d49b590d89920152fff9b254d9fa801b.
=> Remove the Blank protocol in favour of a Size protocol

getting-started/basic-types.markdown
Just started with the "Getting started" section and coming from a JavaScript background got quite hung up on the sudden introduction of arities. Let me know if you have any other suggestions and I'll update my PR!
=> Add short paragraph about arity in getting started/basic types chapter

getting-started/structs.markdown
=> Fix error message for missing key in Structs

getting-started/module-attributes.markdown
=> Edits in the module attributes chapter

getting-started/structs.markdown
=> Error message updated in structs.markdown

getting-started/try-catch-and-rescue.markdown
Only Oxford commas in this one.
=> Edits in the try/catch/rescue guide

_includes/bottom.html
So we don't need to update the footer every new year.
Improved version of https://github.com/elixir-lang/elixir-lang.github.com/pull/914
Additionally replaced the hyphen with an en-dash to separate the years
(that's the proper way of writing years lapses).
/cc @tony612
=> Dynamically update year based on last site build

.gitignore
As explained in https://github.com/jekyll/jekyll/issues/3595
=> Ignore .jekyll-metadata

getting-started/meta/domain-specific-languages.markdown
To correct "Let's see how those different DSLs would look like" to "Let's see what those different DSLs would look like".
=> Correct "how... like" to "what... like"

getting-started/keywords-and-maps.markdown
=> Clarify keywords-and-maps.markdown

getting-started/processes.markdown
=> Clarified getting-started/processes.markdown

_posts/2012-08-01-elixir-v0-6-0-released.markdown, getting-started/mix-otp/supervisor-and-application.markdown
I was on the Elixir slack and saw a bot with a message about this: https://rocketvalidator.com/s/a1508cd6-02d1-4129-b8e8-4e0a7df109b5/p
Not sure how serious this is taken but I figured I might as well help considering the site is where I first started learning Elixir.
=> some accessibility issues

_includes/important-links.html
=> Include Elixir's Discord Server on Join the Community

getting-started/module-attributes.markdown
Nothing important, most people will see it, still should be fixed to default localhost ip
=> Fix example ip

getting-started/mix-otp/genserver.markdown
=> Clarify which argument from start_link/3 is used by init/1 (#975)

getting-started/mix-otp/task-and-gen-tcp.markdown
Should close #945. \cc @jeffdeville
=> Mention how to not hardcode the port in the TCP server

getting-started/case-cond-and-if.markdown
Makes sense after elixir-lang/elixir#5167 :)
=> Be less verbose on guards and point to the "Guards" page in the docs

getting-started/mix-otp/agent.markdown
According to:
https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html#start_supervised/2
=> Change start_supervised arity

getting-started/mix-otp/supervisor-and-application.markdown
"It is the time we change that" is an awkward phrase, subbed it out for "It is time we change that"
=> Language edit

getting-started/introduction.markdown
As a new reader:
* "if you still haven't installed Elixir": what do you mean "still"? This is the very first chapter of the very first introductory page.
* "run to our installation page": wording is a bit weird; I also prefer a more dignified pace of clicking hyperlinks :)
=> Minor language in introduction.markdown

getting-started/processes.markdown, getting-started/try-catch-and-rescue.markdown
Messages changed by: 
https://github.com/elixir-lang/elixir/commit/9ea814f3206721703ebf16977d08e176eb1e7556#diff-9e50910893ff9df17cdef7cc055397f4R248
https://github.com/elixir-lang/elixir/commit/20e2f133d71a36dc6d824ca974fc292ec07ec0db#diff-6bf697cfce89d8072ae720a3aa4b7e2bR61
etc.
=> Process exiting messages etc.

getting-started/keywords-and-maps.markdown
they are -> are they, previous version didn't sound correct 🎈
=> Minor wording change

_posts/2017-11-24-whats-in-master.markdown
Hey @josevalim, here is a draft of the "What's New" post.  I removed the Ecto and Plug changes following our conversation and trimmed things down further after soliciting feedback on Slack.  
Now this is basically the changelog, is that a sufficient place to start?  Are there things you want to mention as "Coming soon"?  We discussed setting up a forum post for each of these, if you'd create that post I will happily update the placeholder.
I'll leave it up to you if you want to include upcoming conferences or blog posts about the features outlined.
=> Initial post outlining changes in master

getting-started/introduction.markdown
Just a few slight changes to the introductory paragraph. I got confused while reading through and thought "foundation" was referring to an actual organisation like several other open source foundations. I've clarified the intent of that passage, and hopefully this should avoid any similar future confusion.
I discussed this with user `asonge` on the `#elixir-lang` freenode IRC and they recommended I make a PR, so here it is 🙂
=> Clarified Introduction Phrasing

_posts/2018-01-17-elixir-v1-6-0-released.markdown
=> Fix `mix profile.*` links in v1.6 announcement

getting-started/mix-otp/introduction-to-mix.markdown
Addressing issue #1077. Thanks for excellent guides @josevalim and elixir-lang community.
=> Update module name from Mixfile to MixProject in Mix and OTP section

getting-started/mix-otp/agent.markdown
Updated error message to include the actual module name.
=> Minor change in Agent chapter

getting-started/basic-operators.markdown
Next chapter is about pattern matching and the match operator, not type conversion and control flow.
=> Right preview of next chapter in 'basic operators'

getting-started/basic-operators.markdown
Sorry, I should have spell checked before submitting the previous PR
=> Fix typo in 'Basic operators'

getting-started/mix-otp/dependencies-and-umbrella-projects.markdown
Noticed this. Thought I'd fix it. 😄
=> Small typo fix in Deps and Umbrella guide

getting-started/enumerables-and-streams.markdown
Show assignment with the pipe operator
=> Show assignment with the pipe operator

getting-started/basic-types.markdown
**Reason:** The real return have more information.
**Note:** I run elixir version 1.6.6.
=> fix / the return for example code

_data/getting-started.yml
**Reason:** The title used in the side menu is different from the title of the page.
=> fix / the titles in the side menu

getting-started/case-cond-and-if.markdown
**Reason:** The real return have a different information.
**Note:** I run elixir version 1.6.6.
=> fix / the return for example code and the title page

getting-started/mix-otp/ets.markdown
Former text could give misleading impression on how to resolve interprocess communication problems.
I am also not sure whether the test "removes bucket on crash" behaves deterministically.
Agent.stop/2 is a sync method, which means that by the time the shell receives control the bucket is down; but can we be sure that the registry receives the message about bucket being `:DOWN` before it receives the message `:create`?  If it was deterministic messages should be sent in the following order:
1. Shell sends `:shutdown` to the bucket;
2. VM sends `:DOWN` message to the registry;
3. Shell sends `:create` message to registry.
Above order ensures that the test is deterministic.
I have not found the proper documentation to support my claim, but can't the order be as following?
1. Shell sends …
=> Clarify ambiguity in race conditions

learning.markdown
Added exercism.io Elixir Track
Adds a link to the Exercism.io site for Elixir.
=> Added exercism.io Elixir Track

learning.markdown
It's a few years old now and people are reporting that it's out of date. If I get the time (and desire) I'll update it and then add it back. For now - it's probably best if I remove.
=> Removing Take Off With Elixir

install.markdown
Install instructions are the same.
=> Add Ubuntu 18.04 to install instructions

getting-started/typespecs-and-behaviours.markdown
- Added information about @impl with code examples and links to the official docs.
Feedback would be appreciated.
=> Added information about @impl

getting-started/binaries-strings-and-char-lists.markdown
I mentor Elixir on Exercism.io and one of my students had failed to understand codepoint usage.
This should make things a little clearer.
=> Added some extra details on codepoints.

getting-started/mix-otp/dynamic-supervisor.markdown
=> The bucket supervisor - Grammar correction

getting-started/io-and-the-file-system.markdown
I think this is interesting to notice explicitly.
=> File.close terminates its process.

getting-started/structs.markdown
I'm not sure if this is a feature or a bug, but if a feature, it does no harm documenting it.
=> mention mixing both implicit and explicit defaults

getting-started/alias-require-and-import.markdown
understood this when reached GenServer.
=> stress the difference use/(alias, import, require)

getting-started/mix-otp/introduction-to-mix.markdown
I think this is the correct place to mention it, since it's the first time we start iex inside the project.
=> mention IEx.Helpers.recompile

getting-started/mix-otp/dynamic-supervisor.markdown
for people coming from object oriented languages, these points are quite tricky indeed.
=> clarify hidden points

_includes/important-links.html
I have updated the widget in the important links sections to reflect this.
=> The early bird tickets are over for the Code Elixir LDN conference

_data/getting-started.yml, _includes/search.html, _posts/2019-06-24-elixir-v1-9-0-released.markdown, getting-started/mix-otp/config-and-releases.md, getting-started/mix-otp/dependencies-and-umbrella-projects.markdown, getting-started/mix-otp/distributed-tasks.markdown, getting-started/mix-otp/docs-tests-and-with.markdown, getting-started/mix-otp/introduction-to-mix.markdown
There is a whole new chapter on the Mix & OTP guides about config and releases. The official announcement still has to be written though.
=> Announcement and updates to Elixir v1.9

getting-started/processes.markdown
=> Minor typo in processes.markdown

getting-started/mix-otp/config-and-releases.markdown
* '--config' flag is deprecated
* received 'Connection attempt from disallowed node :"foo@computer-name"' when the cookie option was not set on the releases
=> Updating Documentation on Config and Releases

_posts/2020-01-27-elixir-v1-10-0-released.markdown
=> Fix typo in v1.10 release post

getting-started/protocols.markdown
=> Fix typo on protocols.markdown

_includes/conferences.html
Changed dates for ElixirConf EU and removed CodeBEAMSF, as this has now finished.
Thanks
=> Change of ElixirConf EU dates due to Coronavirus

_includes/bottom.html, _includes/top.html, css/style.css
Adds a banner at the top of the page.
1. Added in the `top` partial -  displays on every page.
2. `x` button closes it (with a small animation)
=> Add survey link banner

README.md
Reference: https://www.w3.org/TR/html52/textlevel-semantics.html#elementdef-kbd
> When the kbd element is nested inside another kbd element, it represents an actual key or other single unit of input as appropriate for the input mechanism.
=> Use double <kbd>

getting-started/binaries-strings-and-char-lists.markdown
I propose to insert two missing words and replace one period with a colon. Colons introduce your codeblocks.
=> three small typos

getting-started/module-attributes.markdown
instead of Application.get_env
=> use Application.compile_env

getting-started/modules-and-functions.markdown
A small suggestion to double down to show the function head for people who haven't encountered them before.
I read the explanation on line 234 yet was confused when I saw the function head in the example. (I didn't connect it to the explanation.)
=> A comment for function head

getting-started/mix-otp/ets.markdown
The `@impl true` is to keep consistency, and the file path mention is to make the reading less laborious. :grin:
[ETS Guide](https://elixir-lang.org/getting-started/mix-otp/ets.html)
=> improve clarity and add missing code

getting-started/binaries-strings-and-char-lists.markdown
=> Fix a typo

getting-started/typespecs-and-behaviours.markdown
Update "functionalty" to "functionality"
=> Fix documentation typo

_posts/2017-10-31-stream-data-property-based-testing-and-data-generation-for-elixir.markdown
=> Fix typo in StreamData post

getting-started/case-cond-and-if.markdown
Updated to use slightly smoother phrasing.
=> Update case-cond-and-if.markdown: slightly smoother phrasing

learning.markdown
Corrected a grammar issue in my course listing.
=> update learning.markdown - grammar fix

getting-started/mix-otp/supervisor-and-application.markdown
If my understanding of this is correct...
=> small wording change re: supervisor trees

crash-course.markdown
It streamlines the name of the operators used in the Elixir docs.
It adds xor operator.
=> Update Operators table in Crash Course

getting-started/mix-otp/config-and-releases.markdown
At this point of tutorial the release with our application is working, but only partially. This information is implicit and I'm making it explicit, by making a request with valid input and describing it.
=> Add more info to the Assembling multiple releases

getting-started/mix-otp/introduction-to-mix.markdown
This is the updated description of `mix new` accordingly to the issue #1521.
=> Update mix new description (#1521)

getting-started/mix-otp/introduction-to-mix.markdown
"doctest/1" ->"doctest/2"
"test/2" ->"test/3"
=> update link texts

getting-started/basic-types.markdown
Not a native English speaker, so feel free to dismiss this pull request if it's not valid. 🙂
=> Improve grammar of sentence

_includes/conferences.html
Hello.
This PR adds ElixirConf to the conferences list.
=> Add ElixirConf 2021 to conferences

getting-started/modules-and-functions.markdown
The capture operator is introduced here, but it's not explicitly stated what that operator is. I was reading through this part of the getting started guide and was a bit confused as I had to understand the new concept (capture operator) which is already used in the code snippet just above, I think this makes it more clear that it's the same thing you just saw in the code snippet.
=> Explicitly state what the capture operator is

getting-started/typespecs-and-behaviours.markdown
Behaviours and Protocols both seem to work like Interfaces (in OOP based languages), so perhaps it might make sense to mention the differentiation aspect between the two.
Also, IIUC, behavior's seem more like an Interface and Protocols seem like Subclassing (because there can be a default implementation there).
=> behaviour-protocol

getting-started/mix-otp/config-and-releases.markdown
Might just be me but I really struggled to understand the runtime config setup and feel like this could be useful to others.
=> Mention other runtime configuration strategies

crash-course.markdown, getting-started/alias-require-and-import.markdown, getting-started/mix-otp/dynamic-supervisor.markdown, getting-started/typespecs-and-behaviours.markdown, js/toc/README.md
This is a copy of https://github.com/elixir-lang/elixir/pull/12119 for the website documentation.
I have not updated anything in `_posts/` as I do not see a strong justification for updating historical content.
=> Add commas to bare usage of "however" where appropriate

_posts/2022-10-05-my-future-with-elixir-set-theoretic-types.markdown
Hello,
I just noticed some minor typos in the set theoretic type article.
Great write-up!
=> Fix small typos in post

getting-started/io-and-the-file-system.markdown
P.S. Please add the _hacktoberfest_ topic to the repository or add the _hacktoberfest-accepted_ label to the PR if you accept it, thanks!
=> Fix typos in the "IO and the filesystem" chapter

getting-started/try-catch-and-rescue.markdown
- Fix some typos.
- Update error messages to match the current Elixir version.
=> Update the "try, catch, and rescue" chapter

getting-started/mix-otp/dependencies-and-umbrella-projects.markdown
=> Update the "Dependencies and umbrella projects" chapter

getting-started/mix-otp/distributed-tasks.markdown
- Update output messages to match current Elixir version.
- Fix typos.
=> Update the "Distributed tasks and tags" chapter

getting-started/mix-otp/config-and-releases.markdown
- Update outputs to match current Elixir version.
=> Update the "Configuration and releases" chapter

install.markdown
https://github.com/chocolatey-beam/elixir-package
=> Add chocolatey install instructions

getting-started/meta/quote-and-unquote.markdown
This made it easier to understand for me since we can directly compare the functionality. What do you think?
I don't have time for reformulating the text right now, but it could be considered in the future.
=> Suggestion for additional example for Macro.escape

getting-started/typespecs-and-behaviours.markdown
Make variable for file extension consistent across with clauses in behaviour use example.
=> Update typespecs-and-behaviours.markdown w/consistent variable name in example

getting-started/try-catch-and-rescue.markdown
Backporting https://github.com/elixir-lang/elixir/pull/12876
=> Update undefined variable error messages

getting-started/mix-otp/dynamic-supervisor.markdown
See https://github.com/elixir-lang/elixir-lang.github.com/issues/1712
=> remove not working markdown for hint/warning

_includes/important-links.html
@josevalim I can't reopen a [closed pull request](https://github.com/elixir-lang/elixir-lang.github.com/pull/1719) (which is actually a good feature 😂) so here is one that adds that link, per https://github.com/elixir-lang/elixir-lang.github.com/pull/1719#issuecomment-1695981662
Here is what the wiki looks like:
Thanks! ❤️
=> Add hiring section

_posts/2021-07-29-bootstraping-a-multiplayer-server-with-elixir-at-x-plane.markdown
=> Fix broken link

install.bat, install.sh
* Allow OTP 28 for Elixir 1.19
* Fix `> install.bat elixir@main`
* Fix `> install.bat otp@latest`
=> Update install.sh and install.bat
