- install.markdown
I added Fedora instructions to install.markdown.
As of Fedora 17, Elixir is in the default repos.
> Added Fedora

- getting_started/8.markdown
Exactly what @nedzadarek described in #399 :smile:.
> Example of default args being always evaluated (ch. 8, Modules)

- getting_started/10.markdown
I added a brief description of the pipe operator (`|>`) in chapter 10, when it is first used. This has been suggested by @josevalim in #395.
> Brief description of the pipe operator in chapter 10

- _includes/bottom.html
- js/toc/README.md
- js/toc/toc.js
This PR downgrades Jquery to 1.x. there is no need to run 2.x since we only use it for Jekyll TOC, and 2.x support less browsers.
Also I have updated Jekyll TOC to the latest version,
Now we can directly use the code in their repository, after having submitted these improvements, https://github.com/ghiculescu/jekyll-table-of-contents/pull/9
> Downgrade jquery + Update Jekyll TOC

- _includes/learning-resources.html
- css/style.css
Remove the border from the images on the right-hand side-bar (some book covers end up with a double border), and only add it through a "border" class  to the ones that needed.
> simplify css border images on widgets + remove border from book covers

- getting_started/18.markdown
- Added an additional example of using the `:into` option with a map to "map"
over the map values
- Rephrased some sentences
Most changes are justified in the diff's comments.
**NOTE** if this is going to be merged, let me know **BEFORE** merging since I made a small typo and committed it. I could `push --force` but I'd lose the diff comments, so just give me a thumbs-up and I'll `push --force` over the commit so that you can merge. Sorry for this :disappointed:
> Added some examples and rephrased some stuff in ch. 18

- _layouts/getting_started.html
- getting_started/20.markdown
- getting_started/21.markdown
I stubbed a first draft of a possible chapter about behaviours. I saw that #31, the issue about such chapter, is quite old (mid 2012!), but it looks like it's never been tackled.
I pushed a "draft" commit, so that you can have a look at how things have came out. I'm actually not 100% sure you still need a chapter about behaviours (or **only** about behaviours, for that matter). I positioned the chapter as the last one (21) in the getting started guide navigation, but didn't actually number it (the file is called `behaviours.markdown` and the sections are numbered as `x.1` and `x.2`).
Let me know what you think of all this :smiley:. Thanks!
> Chapter about typespecs and behaviours

- _layouts/getting_started.html
- getting_started/17.markdown
- getting_started/18.markdown
- getting_started/19.markdown
The chapter about try/catch/rescue, which was chapter 17 before this commit, has been moved to chapter 19, and the chapters about comprehensions and sigils (18 and 19 respectively) have been scaled down (17 and 18 now).
This should close #413.
> Move the try/catch/rescue chapter after the sigils one

- getting_started/16.markdown
PR #421 moved the try/catch/rescue chapter to chapter 19 (it was chapter 17 before), but the last sentence of chapter 16 still mentioned that in the next chapter errors would be covered. That is not true anymore.
(Sorry, my bad :disappointed:)
> Remove an outdated sentence from chapter 16

- _layouts/getting_started.html
- getting_started/12.markdown
Chapter 16 was called just "IO" but explained both how to do IO in Elixir as well as how to interact with files and the filesystem (the `File` and `Path` modules). The new title - "IO and interacting with the filesystem" - reflects exactly that.
I also fixed a bunch of grammar/spelling errors throughout the file and rephrased some sentences here and there. There are a few comments in the diff justifying the changes :smile:.
> Rename chapter 16 and fix a bunch of errors in that chapter

- getting_started/meta/1.markdown
I added an additional code sample showing what happens when you don't `unquote` a value but you want to inject that value in a quoted expression.
> Add more details to unquoting in meta/chapter-1

- css/style.css
I have stuggled many times to distinguish whether it was inline code or not.
Before:
After:
> add border to inline code style

- getting_started/11.markdown
- getting_started/12.markdown
- getting_started/13.markdown
- getting_started/14.markdown
- getting_started/15.markdown
- getting_started/19.markdown
- getting_started/21.markdown
- getting_started/5.markdown
- getting_started/7.markdown
- getting_started/8.markdown
- getting_started/mix_otp/1.markdown
- getting_started/mix_otp/10.markdown
- getting_started/mix_otp/2.markdown
- getting_started/mix_otp/3.markdown
- getting_started/mix_otp/4.markdown
- getting_started/mix_otp/5.markdown
- getting_started/mix_otp/8.markdown
- getting_started/mix_otp/9.markdown
* Slight improvements to MIX & OTP Guide, Chapter 1 and 2.
* `<abbr>` added for VM, EEP and OTP. And first time mentioned, give the full meaning in text.
* Capture operator example added when calling Modules.
> Mix otp improvents + <abbr> added

- _includes/index-redirect.html
- getting-started/index.html
- getting-started/meta/index.html
- getting-started/mix-otp/index.html
This addition solves the issue of visiting a the folder, with no index.html
http://elixir-lang.org/getting_started/mix_otp/ well, now http://elixir-lang.org/getting-started/mix-otp/
where should it go.
This include file read _data/getting-started or whatever file you want, look in the document structure for the current folder, and gives redirects you to the first article.
I created it from scratch. And I think it can be reused in other jekyll projects
> index-redirect.html added

- getting-started/where-to-go-next.markdown
Mentioned the meta-programming guide in the last chapter of the Getting Started guide, "Where to go next". This should close #447.
> Mention the meta-programming guide

- getting-started/mix-otp/docs-tests-and-pipelines.markdown
I noticed `choosing` had a spelling error.  But then I looked at it a bit more and thought it could use a bit of rephrasing in general in that sentence and the transition to the next.
> Rephrase a bit in `Docs, tests and pipelines` (Mix and OTP guide)

- install.markdown
Elixir is now on the official Arch Linux repositories and can be installed using the default pacman package manager instead of requiring manual building or the use of the yaourt package manager.
> updated installation instruction for Arch Linux

- css/style.css
some dimensions in px are converted to em,
and fixes other that I have incorrectly calculated in the previous commit
> correct EM dimensions

- crash-course.markdown
- Fix some capitalizations
- Uniform the style of not using spaces around curlies
- Add an example of an Elixir atom (`:""` to match the Erlang example of `''`)
Let me know if I can do anything else!
> Minor polishes in the "Crash course" guide

- getting-started/case-cond-and-if.markdown
removes the gaps inside the bullet list
http://elixir-lang.org/getting-started/case-cond-and-if.html#expressions-in-guard-clauses
> remove gap in lists

- getting-started/mix-otp/genserver.markdown
As per our discussion here: https://github.com/elixir-lang/elixir-lang.github.com/issues/511
There is an error where list is used in the Agent.start_link KV example rather than a HashDict, as per the bucket.ex example.
First pull request! Exciting!!
> Fixed mix-otp/genserver typo

- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
Thanks for writing these comprehensive getting-started guides!
> Quick typo fix: successfuly -> successfully

- getting-started/io-and-the-file-system.markdown
“...writes to the standard-**input** file descriptor:” > “...writes to the standard-**output** file descriptor:”
> Fix typo “…writes to the standard-input…” > standard-output

- getting-started/basic-types.markdown
- getting-started/binaries-strings-and-char-lists.markdown
- getting-started/case-cond-and-if.markdown
- getting-started/introduction.markdown
- getting-started/meta/macros.markdown
- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- getting-started/mix-otp/genevent.markdown
- getting-started/mix-otp/introduction-to-mix.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
- getting-started/sigils.markdown
Stuff I started checking only halfway through the first pass.
> Caps and code block language hint

- getting-started/comprehensions.markdown
One of the examples in the comprehension Getting Started guide contained a potentially destructive operation on the filesystem.
This commit replaces that operation (File.rm!/1) with a function that poses no risk to the files of a user following along (File.stat!/1).
> Remove potentially destructive comprehension example in Getting Started guide

- Gemfile
- Gemfile.lock
- README.md
- _includes/index-redirect.html
- fix URL in index-redirect
- add anchor to localhost:4000 in README
- remove all plugin dependencies, except "github-pages": We shouldn't install anything, we should leave it all upto github-pages plugin, same as it happens in the github servers.
> Several fixes

- _includes/code-editor-support.html
@josevalim We already had this discussion about adding it to the elixir-lang website and then it was not really a need.
But since Alchemist really getting to a decent point in case of usefulness I think it would be a good idea to add it.
What do you think?
Cheers
Samuel
> add alchemist to the editor support

- getting-started/mix-otp/task-and-gen-tcp.markdown
The method `defp serve(socket` is shown in a number of code
snippets. The first one uses a variable `client` while every later
version names that variable `socket`:
```
getting-started/mix-otp/docs-tests-and-pipelines.markdown:defp serve(socket) do
getting-started/mix-otp/docs-tests-and-pipelines.markdown:defp serve(socket) do
getting-started/mix-otp/docs-tests-and-pipelines.markdown:defp serve(socket) do
getting-started/mix-otp/task-and-gen-tcp.markdown:defp serve(client) do
getting-started/mix-otp/task-and-gen-tcp.markdown:  defp serve(socket) do
```
> docs, name variables consistently across iterations. [ci skip]

- getting-started/mix-otp/supervisor-and-application.markdown
Just a little thing. It isn't obvious where this module should be defined. I first tried putting it in `lib/kv/bucket.ex` but the lookup doesn't check there.
> Clarify location of KV.Bucket.Supervisor

- getting-started/processes.markdown
This is super minor, but I figured I'd correct it anyway.
> Minor grammar fix on processes

- getting-started/maps-and-dicts.markdown
Reinforce that 'Maps allow any *value* as a key' means that variables are not allowed as keys.
This came up on irc and I thought the docs could be clearer.  Once you think about what "value" means in context, it's obvious, but the first time through it may not be.
> Note that variables cannot be used as map keys.

- getting-started/case-cond-and-if.markdown
In the first example for `case`, we learn that underscore "would match any value".
It's then confusing to read in the third example that underscore "won't match".
While this is technically true in the example as written, (since x>0, the first pattern will match,) it's not consistent with the earlier statement.
> Clarify that underscore would match if it were reached in execution.

- getting-started/maps-and-dicts.markdown
This came up in #elixir-lang today and my initial patch needs to be clarified.
Thanks to @ericmj for explaining that while variables cannot be used to _add_ items to a map, they _can_ be used to _access_ items in a map.
> Clarify that variables can be used to access items in a map.

- getting-started/io-and-the-file-system.markdown
Currently rendered as a double backslash on http://elixir-lang.org/getting-started/io-and-the-file-system.html.
Also confirmed that GitHub renders it double if doubled, and renders it fine if single.
> Don't double-escape backslash

- docs.markdown
this fixes the issue of 
http://elixir-lang.org/docs/v1.0/
not linking properly to the HEADING
> add element id v1.0 to fix issue with redcloth replacing Header ID

- README.md
- _includes/important-links.html
- _includes/search.html
- _includes/top.html
- _posts/2012-04-24-a-peek-inside-elixir-s-parallel-compiler.markdown
- _posts/2012-05-25-elixir-v0-5-0-released.markdown
- _posts/2012-08-01-elixir-v0-6-0-released.markdown
- _posts/2012-11-18-elixir-v0-7-1-released.markdown
- _posts/2013-05-02-elixir-on-xen.markdown
- _posts/2013-05-23-elixir-v0-9-0-released.markdown
- _posts/2013-08-08-elixir-design-goals.markdown
- _posts/2014-04-21-elixir-v0-13-0-released.markdown
- _posts/2014-08-07-elixir-v0-15-0-released.markdown
- _posts/2014-09-18-elixir-v1-0-0-released.markdown
- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/introduction-to-mix.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
- getting-started/recursion.markdown
- getting-started/where-to-go-next.markdown
- index.html
* update URL where the used http link redirects to https, and as well when a package is provided and the https link is available.
* standardize erlang.org/doc links to use www
> update url to use https. standardize erlang.org/doc links to use www

- crash-course.markdown
I was trying to understand someone else's code and did not know what `\\` was for.
I had trouble finding this information. When I found it (I think I resorted to Sublime 'Find in files' on the docs repo because I knew it had to be here somewhere) then I wanted to link to it, and I couldn't.
Adding a section header will give it an anchor and make the info on the syntax for default values more prominent.
> Promote default values to its own section

- getting-started/case-cond-and-if.markdown
I found this the hard way. I was relying on the list of this page, to realized that we were missing some functions/macros that are allowed in guards.
I have added the word  "macros" now since there is more than just one (is_nil)
@josevalim @ericmj I have the feeling that we need a helper function in elixir that lists the functions that are allowed in guard.
how about having: `Kernel.allowed_in_guard?(module, function_name, arity)` and  `Kernel.list_allowed_in_guards/0`
I think relying on a an external website to know what can be used in guards,
Regardless creating the helper functions, I think we need to create the list that we have in this page, in the elixir documentaion itself.
> add missing is_* macros

- getting-started/mix-otp/ets.markdown
I ran into this and it was hard to find the bug, while going through the tutorial.
The error message was not very helpful for me:
(KeyError) key :event not found in: %{buckets: #PID<0.146.0>, events: #PID<0.147.0>, names: 340007, refs: #HashDict<[{#Reference<0.0.4.142>, "shopping"}]>}
I don't understand why it's missing an :event atom instead of an event variable?
> Missing s character.

- getting-started/maps-and-dicts.markdown
> Remove duplicate "the" in the "Keywords, maps and dicts" page

- getting-started/module-attributes.markdown
Hello again!
As I'm advancing in the getting started guide, I thought a little link to the ExUnit library documentation might be useful in the "Module attributes" (ch. 14) page! :boom: 
Cheers!
> Add a link to the ExUnit documentation

- getting-started/enumerables-and-streams.markdown
A couple coworkers of mine attended the Phoenix training in Austin last week. Prior to that their only Elixir experience was the getting started guide.
One if them mentioned this:
>By the way, about half-way through the second day of the training, Niko and I both had a revelation about understanding the `|>` operator...  The fact that it just passes the value in as the first argument.
>Watching the code and thinking about it, some of the time we passed 3 args, and then sometimes 2 args, and while we got what the pipe operator does (generally speaking), the code was still hard to follow until that revelation...
>The intro docs say "it simply takes the output from the expression on its left side and passes it as the input to the function call on its right side."
>But . . . that really …
> pipe operator clarification

- getting-started/mix-otp/genserver.markdown
Working through the docs, I read "To shutdown the registry, we are simply sending a `:shutdown` signal to its process when our test finishes."
However the code doesn't have any explicit :shutdown signal being sent.  
@antipax explained on irc that this happens automatically.
> The :shutdown signal is sent automatically

- getting-started/try-catch-and-rescue.markdown
Could be more helpful.
Symbols instead of bools in the example because I think it reads clearer here.
> try-catch-and-rescue "Variables scope": offer alternative

- getting-started/comprehensions.markdown
@josevalim : I tried my best to give a representation of multiple generators but I am not sure whether its up to the mark you expected. Please do a review and let me know if something else has to be changed/added/removed.
I can see you are not available on IRC but there was one more point where I am not clear which way to represent i.e. *traversing*. A classical example of that could be 
```
iex> for user <- [%{name: "Me", phones: ["123", "345"]}], do: (for phone <- user.phones, do: phone)
```
or the same code can be written as (without nested output)
```
iex> for user <- [%{name: "Me", phones: ["123", "345"]}], phone <- user.phones, do: phone
```
> Multiple generators in comprehension

- index.html
This could have alternatively been changed to: `Supervisor's got your back!` However, it seemed more likely to me that it was intended to refer to supervisor processes and not the Supervisor module.
> Resolve ambiguous grammar

- _config.yml
- index.html
This replaces typewriter quotation marks and apostrophes with typographic ones. It uses Redcarpet's _smart_ extension for markdown.
For example:
would become:
> Use typographic punctuation throughout

- getting-started/binaries-strings-and-char-lists.markdown
The last test in [&ldquo;The string type is broken&rdquo;](http://mortoray.com/2013/11/27/the-string-type-is-broken/) is for the comparison of two logically equivalent strings with different compositional forms (e.g., `"noe\u0308l"` and `"noël"`).
> Indicate that Elixir passes all but one string test indicated in link

- _posts/2015-09-28-elixir-v1-1-0-released.markdown
Escape `_`'s in the Code of Conduct link so that it doesn't use italics
> Fix Code of Conduct markdown link escape chars

- getting-started/modules.markdown
If the previous instructions were followed verbatim, some output would not be displayed. Additionally, `iex` would crash upon reaching `UndefinedFunctionError`.
> Clarify Getting Started > 8. Modules

- getting-started/mix-otp/agent.markdown
"peeking at" the implementation vs "peeking" the implementation.
> Add a missing preposition to the Agent guide.

- getting-started/basic-operators.markdown
`error` is an undefined function and raises a `CompileError`. Use `raise` instead
> Fix incorrect documentation

- getting-started/try-catch-and-rescue.markdown
Wasn't clear to me that you didn't have to provide the error struct.
> try-catch-and-rescue: skipping error struct

- getting-started/alias-require-and-import.markdown
I was reading the "Getting started" guide and one of the things I noticed is that the section where `require`, `alias` and `import` are documented doesn't include any explanation for `use`. In fact, `use` is not mentioned at all in the entire getting started guide.
I know [`import`, `require` and `alias` are `SpecialForm`](http://elixir-lang.org/docs/v1.1/elixir/Kernel.SpecialForms.html) whereas `use` is [defined as `Kernel` macro](http://elixir-lang.org/docs/v1.1/elixir/Kernel.html#use/2), however it's not uncommon to see new users confused by this specific keyword: see [here](http://stackoverflow.com/questions/28491306/elixir-use-vs-import) and [here](http://stackoverflow.com/questions/29097918/elixir-what-does-the-use-keyword-do).
This branch takes bits and pieces from the answers …
> Add a short documentation for `use`

- getting-started/mix-otp/genserver.markdown
Remove an extra "instead" word in the GenServer chapter of Getting Started
> Fix extra word typo

- getting-started/comprehensions.markdown
Renamed Pythagorean “triplets” to the more common “triples”. Also indicated that the optimization to `Triple.pythagorean/1` filters duplicate triples out of the results.
> Clarify pythagorean triple function

- getting-started/io-and-the-file-system.markdown
`File.rm_rf` has an arity of 1 (https://github.com/elixir-lang/elixir/blob/v1.1.1/lib/elixir/lib/file.ex#L836),
but the getting started guide lists it as 2.
> Fix `File.rm_rf` arity.

- getting-started/modules.markdown
Body-less function head is required (not optional) for multiple clauses
with defaults. Without the head following error raised by compiler
```
== Compilation error on file lib/mnesia/key_gen.ex ==
** (CompileError) lib/mnesia/key_gen.ex:18: def slug/3 has default values and multiple clauses, define a function head with the defaults
lib/mnesia/key_gen.ex:18: (module)
(stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```
> Mandatory function head

- getting-started/mix-otp/introduction-to-mix.markdown
The Introduction guide sets Elixir version 1.0.0 as the minimum requirement, so the Mix Introduction guide should match the same required version - it's likely what users will have installed anyway.
> Update note about required Elixir version to match the Introduction guide

- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
Otherwise the tests can fail because the compiled BEAM files are different (and the anonymous functions won't run across nodes).
> Use MIX_ENV=test when starting `bar` for the tests

- install.markdown
As `yum` is now replaced with `dnf`, the install instructions where not up to date.
It might be considered to remove the fedora 17 section all together, as only Fedora 21 packs it and older versions are [not maintained anymore.](https://fedoraproject.org/wiki/End_of_life?rd=LifeCycle/EOL). Fedora 21 EOL is in less than a week, december 1st.
> Update fedora install instructions

- getting-started/mix-otp/supervisor-and-application.markdown
I was having trouble with this part, until I read the explanation in the Erlang documentation where it explains `start_child/2`.
> complement the explanation for :simple_one_for_one

- getting-started/alias-require-and-import.markdown
- getting-started/binaries-strings-and-char-lists.markdown
- getting-started/comprehensions.markdown
- getting-started/enumerables-and-streams.markdown
- getting-started/introduction.markdown
- getting-started/io-and-the-file-system.markdown
- getting-started/maps-and-dicts.markdown
- getting-started/module-attributes.markdown
- getting-started/processes.markdown
- getting-started/recursion.markdown
- getting-started/sigils.markdown
- getting-started/try-catch-and-rescue.markdown
- getting-started/where-to-go-next.markdown
Minor changes to some of the grammar and punctuation in the
Getting Started Guide.  Hopefully nothing too opinionated,
a comma here, a word change there. Intended to make the guide
clearer, and improve readability.
> Changed some grammar and punctuation in Getting Started Guide

- _includes/code-editor-support.html
I just noticed there was a side-menu for editors, so adding my IntelliJ Elixir plugin to the list.
> Add IntelliJ Elixir to Code editor support

- getting-started/mix-otp/introduction-to-mix.markdown
the tests generated by `mix` now include an extra line (`doctest KV`), so the line numbers were off by 1.
> update line numbers for the default test

- getting-started/mix-otp/supervisor-and-application.markdown
I have been going through the mix-otp guide and got stuck at the `removes bucket on crash` test. The `assert_receive` fails with the following:
```
1) test removes bucket on crash (KV.RegistryTest)
test/kv/registry_test.exs:26
No message matching {:exit, "shopping", ^bucket} after 100ms.
The following variables were pinned:
bucket = #PID<0.117.0>
The process mailbox is empty.
stacktrace:
test/kv/registry_test.exs:31
```
I am super new to Elixir (it is awesome, thank you!) so I may be way off on this, but from a bit of investigating I think that this example previously used `GenEvent` to deliver the :exit message that is being waited on, and there is no need to wait for notification now that `GenServers` have the `stop` function.
> Fix getting started supervisor shutdown test

- getting-started/keywords-and-maps.markdown
This make some text considered as code seem well.
That's all.
Thanks to read :)
> add missed ```in 'Getting Started - Keywords and maps'

- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
The code example of an external dependency was for `{:plug}, "~> 1.0"}`, but the text said that the dependency referred to the latest version of Plug in the 0.5.x version series, which I think is old and should be updated to reference the 1.0 version series.
> Fixing typo in dependency paragraph

- getting-started/mix-otp/supervisor-and-application.markdown
The way it its, the image's width is larger than its `<p>` container:
I just added a `width=640px` to the image so that it fits into its container:
> Set width of the kv-observer image to fit better in the desktop

- install.markdown
Elixir 1.2 requires erlang 18. Change the version from 17 to 18.
> Fix install instructions: erlang 18 is required.

- getting-started/mix-otp/docs-tests-and-with.markdown
I believe there's a word missing in:
> Since we have used unit tests so far, this time we will take the other road and write an integration test
That word would be "**only**":
> Since we have **only** used unit tests so far, this time we will take the other road and write an integration test
> Add a missing word

- getting-started/mix-otp/ets.markdown
I've interested in elixir about couple of weeks ago and reading through some books and elixir-lang website. I've encountered with this while reading about ETS. I thought the first `it` is unnecessary and removed it.
By the way, thank you for this nice language.
> Unnecessary 'it' removed

- getting-started/comprehensions.markdown
In the text I changed, in a sentence "filter out" was used to mean "select" and in another to mean "discard" (the opposite). By using select / discard both sentences are correct and clearer.
See https://en.wiktionary.org/wiki/filter_out
> Removed ambiguity about filter: "filter out" means discard.

- getting-started/sigils.markdown
Here is what mentioned on #669, and this is why this pr is sent. :)
"""START"""
Hi. I have one suggestion about one example.
Here is example in [guide](http://elixir-lang.org/getting-started/sigils.html)
```iex
iex> ~s(String with escape codes \x26 #{"inter" <> "polation"})
"String with escape codes & interpolation"
iex> ~S(String without escape codes and without #{interpolation})
"String without escape codes and without \#{interpolation}"
```
This example give comparison between '~s' and '~S', meaning to say,
it may show interpolation and escape work or not clearly on both example.
And to me, this example intend to show how escape work with '\x26',
how interpolation work with '#{"inter" <> "polation"}'.
However, 'and' instead of '\x26' on the second example code, so only reader could see …
> Patch to change 'and' to '\x26'on 'Getting Started#sigils' for better example

- getting-started/binaries-strings-and-char-lists.markdown
Updated to indicate that `String` now passes all the tests in "The string type is broken" (as of Elixir 1.2).
> Update string guide

- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
Usage of `Task.Supervisor.async/4` is meant instead.
Result of running existing example
```
iex(bar@Christophs-MBP)1> Task.Supervisor.async {KV.RouterTasks, :"foo@Christophs-MBP"}, [Kernel, :node, []]
** (EXIT from #PID<0.101.0>) an exception was raised:
** (BadFunctionError) expected a function, got: [Kernel, :node, []]
:erlang.apply/2
(elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
(elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
(stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Interactive Elixir (1.2.0) - press Ctrl+C to exit (type h() ENTER for help)
```
Result of running changed example
```
iex(bar@Christophs-MBP)2> Task.Supervisor.async {KV.RouterTasks, :"foo@Christophs-MBP"}, Kernel, :node, []
%Task{owner: #PID<0.144.0>, pid: #PID<12960.109.0>, ref: …
```
> Fix example code in distributed-tasks-and-configuration

- getting-started/case-cond-and-if.markdown
- getting-started/enumerables-and-streams.markdown
- getting-started/keywords-and-maps.markdown
- getting-started/modules.markdown
- getting-started/processes.markdown
The script output was missing from the example.
Also fixes a few conceptual, grammatical, and spelling errors throughout getting-started.
> Add `spawn_link` script output to example in processes

- _config.yml
- _posts/2012-04-24-a-peek-inside-elixir-s-parallel-compiler.markdown
- _posts/2012-05-25-elixir-v0-5-0-released.markdown
- _posts/2012-08-01-elixir-v0-6-0-released.markdown
- _posts/2012-10-20-elixir-v0-7-0-released.markdown
- _posts/2012-11-18-elixir-v0-7-1-released.markdown
- _posts/2012-12-04-elixir-v0-7-2-released.markdown
- _posts/2013-01-27-elixir-v0-8-0-released.markdown
- _posts/2013-04-19-google-summer-of-code-2013.markdown
- _posts/2013-04-29-elixir-v0-8-2-released.markdown
- _posts/2013-05-02-elixir-on-xen.markdown
- _posts/2013-05-23-elixir-v0-9-0-released.markdown
- _posts/2013-07-13-elixir-v0-10-0-released.markdown
- _posts/2013-08-08-elixir-design-goals.markdown
- _posts/2013-11-05-elixir-v0-11-0-released.markdown
- _posts/2013-12-11-elixir-s-new-continuable-enumerators.markdown
- _posts/2013-12-15-elixir-v0-12-0-released.markdown
- _posts/2014-04-21-elixir-v0-13-0-released.markdown
- _posts/2014-06-17-elixir-v0-14-0-released.markdown
- _posts/2014-08-07-elixir-v0-15-0-released.markdown
- _posts/2014-09-18-elixir-v1-0-0-released.markdown
- _posts/2015-09-28-elixir-v1-1-0-released.markdown
- _posts/2016-01-03-elixir-v1-2-0-released.markdown
Due to the recent jekyll changes I noticed that a permalink for each blog post had to be added. Rather than have that added to every blog post file, this `_config.yml` change provides a default permalink for all `post` types.
> Set a default permalink for blog posts

- index.html
It's featured on http://elixir-lang.org/docs/stable/iex/IEx.Helpers.html of course, but I think it deserves to be on the homepage because it's so convenient
> Mention `iex> i` on the homepage

- getting-started/try-catch-and-rescue.markdown
Someone asked what the "`catch` without `try`" form meant in the IRC channel, and I remembered being confused about it myself when I first saw it.
> Added a section about procedure-level `catch` blocks.

- crash-course.markdown
It's been misleading for a couple of people I've seen working through the crash course to reference modules that don't exist.
I wasn't sure what the best example would be, but I used `List` and `lists` since an example using `List` follows.
> use real modules in crash course

- _data/getting-started.yml
- getting-started/erlang-libraries.markdown
The section was added to it's own chapter, and added to the index near
the end of the main chapters
> Add section showcasing more useful Erlang modules

- docs.markdown
Noticed that this was linking to a slightly out-of-date version. Is there a better way of keeping links like this up to date? (The `/docs/v1.2/.../` links below do redirect to the most recent patch version.)
> link to most recent (v1.2.3) Docs.zip

- getting-started/mix-otp/task-and-gen-tcp.markdown
The presence of a `|` character in a Markdown link on the _Task and gen_tcp_ page was causing the paragraph it's in to render as a table:
Also, the link didn't properly function for me.
I've escaped the entities in it which fixes the rendering:
This also makes the link work in Chrome and Safari.  I was unable to find a way to make Firefox accept it.
> Fix a Problematic Link in the Mix & OTP Guide

- _includes/bottom.html
- css/style.css
I love what @lexmag and @josevalim discussed in #696. How does this implementation look? I haven't tested the proper link locally because GH injects the `site.github` data when it builds the site.
> Add a "Edit on GitHub" link to the footer

- getting-started/sigils.markdown
The macro `sigil_r` was incorrectly identified as a function. One could have merely changed the word _function_ to _macro_. However, the revelation that it is a macro and not a function could pose a distraction and lead to confusion ahead of the final paragraph of the page. Consequently, I chose to remove the word _function_.
> Make correction in “Sigils”

- getting-started/mix-otp/genserver.markdown
Make function calls idiomatic and consistent with the rest of the content.
> Remove empty parentheses from genserver.markdown

- getting-started/mix-otp/introduction-to-mix.markdown
Great project, thank you!
The example for setting a session based environment variable for establishing your Elixir environment is incorrect. 
It uses the `-A` flag which [is for expressions](http://ss64.com/nt/set.html) like setting a variable to the result of '1 + 2'
If you try to use batch with the existing cmd using the /a flag, the output in windows cli is `0` - not set.  My revision will resolve this and is tested on Windows 8.1
> Fix windows set environment cmd

- getting-started/basic-types.markdown
Add reference to capture syntax for anonymous functions so that when going through 'Getting started' in order, you don't get curious at Keywords and maps - Nested data structures, which uses the capture syntax.
> Add reference to capture syntax for anonymous functions

- _posts/2013-05-23-elixir-v0-9-0-released.markdown
- _posts/2013-07-13-elixir-v0-10-0-released.markdown
- _posts/2013-08-08-elixir-design-goals.markdown
- _posts/2013-12-11-elixir-s-new-continuable-enumerators.markdown
- _posts/2014-04-21-elixir-v0-13-0-released.markdown
- crash-course.markdown
- getting-started/basic-operators.markdown
- getting-started/basic-types.markdown
- getting-started/case-cond-and-if.markdown
- getting-started/modules.markdown
- getting-started/pattern-matching.markdown
- getting-started/protocols.markdown
- index.html
Standardizes the use of comma leaving a white space after it whenever applicable.
> Formatting: add white space after comma

- _includes/code-editor-support.html
I just saw that there is no extension for Visual Studio Code users.
> Add Visual Studio extension for Elixir

- getting-started/modules.markdown
Include an example demonstrating a clause failure on floats.
> Modify Math.zero? to specifically process integers. (#722)

- getting-started/case-cond-and-if.markdown
This is a possibly temporary fix for #727. I think we may want to rework the examples some way so that they become clearer, but this is a solution to the problem we're having *now* :)
> Fix the output of some examples in the "Case, cond and if chapter"

- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
While working through the example app, I noticed the `1.2-dev` dependency reference uses the `-dev` release. Now that `1.2` has been released, the documentation should reflect the `1.2` version
> Change `1.2-dev` references to `1.2`

- getting-started/recursion.markdown
The JS in the example is missing a semicolon, so this adds it.
> Adds a semicolon to JavaScript

- getting-started/processes.markdown
http://elixir-lang.org/docs/stable/elixir/Kernel.html#send/2:
> Sends a message to the given dest and returns the message.
Which, in this case, is the tuple.
> the send command returns the tuple, not the #PID

- getting-started/mix-otp/introduction-to-mix.markdown
unecessary -> unnecessary
Many thanks to keep maintain well. :)
> fix typo miss on 'Introduction to Mix'

- getting-started/mix-otp/genserver.markdown
I am not sure why we're using `Map.new` here instead of `%{}`. On the previous page we're using `%{}`, but here we're using `Map.new` for apparently no reason at all.
> Use %{} instead of Map.new in genserver docs

- getting-started/mix-otp/genserver.markdown
Updated the arity to GenServer.start_link/3
> Typo in mix-otp/genserver

- getting-started/case-cond-and-if.markdown
It looks like something got mixed up here, as there's a confusing repetition. I think this is the clearest option to fix it. Alternatively, it could say something like
> `if` needs two arguments - the conditional expression and the `do/end` block.
> Update 'case, cond, and if' page

- getting-started/enumerables-and-streams.markdown
Punctuation; removed two words which are unnecessary and are incorrect English.
> Update enumerables-and-streams.markdown [minor]

- getting-started/recursion.markdown
Because in JavaScript one could write that example in imperative way, but would write that example as
```javascript
array.map(function(el) {
return el * 2;
});
```
Let's just use pure imperative programming language as an example.
> Replace JavaScript example with C

- getting-started/module-attributes.markdown
- update warning message of undefined module attribute
> Explicitly mention double-quotes for Heredocs

- getting-started/introduction.markdown
The Pragmatic "Programming Elixir" book references `http://elixir-lang.org/getting_started/1.html` which has been moved to `http://elixir-lang.org/getting-started/introduction.html`. This PR adds a `redirect_from` on the `introduction.markdown` page to ensure that readers of that book are able to use the URL in the book without getting a 404.
> Redirect old getting started URL

- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- mention correct version of dependency w.r.t correct explanation of Version.
> update specs w.r.t Elixir 1.3

- getting-started/basic-types.markdown
To me, those round brackets imply a causal relationship: "it's a fast operation because indexes start from zero". That's definitely not the case, so I think the punctuation should change.
> Brackets seem to imply something that's not true

- getting-started/basic-types.markdown
The current example does not actually illustrate closure capture of variables in scope at function declaration.
> Make closure example's captured variable explicit

- getting-started/meta/macros.markdown
Hi, I'm shia,
This is updated the indented, not syntax highlighted code to be applied syntax highlight.
meaning to say, indent will not be applied syntax highlight, so it look like blocked, strange T-T
how about give him to be more beautiful?
I can't find the reason why this snippet onl
y indented, not highlighted.
Thanks to read this. :)
> Proposal to highlight indented code

- _includes/search.html
- _posts/2016-07-14-announcing-genstage.markdown
@fishcakez @alco @lexmag @whatyouhide @ericmj, please review it if/when you have a while.
> Announcing GenStage

- getting-started/pattern-matching.markdown
I spent a while trying to figure out why the pattern would match `42` but not `"!"`.  Turns out my browser doesn't show much difference between `[` and `{` so I was concentrating on the more obvious -- but irrelevant -- change.
> simplify the pattern match example

- getting-started/mix-otp/ets.markdown
This is a very small change for consistency's sake.
❤️ 
You can see the case differs from the other comment [here](https://github.com/elixir-lang/elixir-lang.github.com/pull/810/files#diff-8c5f16decd3fd0e493626da2abb4fe46R254)
> Make comments on ETS tests more consistent

- getting-started/basic-types.markdown
It is implied that String.length is expensive, but does not explicitly say it.
> Wording change

- _posts/2016-07-14-announcing-genstage.markdown
Hi folks,
Was reading the 7/14 Announcing GenStage post and noticed a few broken links that were pointing to the hexdocs for `Experimental.GenStage.Flow`, which has since been renamed to `Experimental.Flow`. I left the actual names (`GenStage.Flow`) alone to reflect what the module was called at time of writing.
> fix broken Flow hexdocs links

- crash-course.markdown
> minor typo in crash-course.markdown

- getting-started/basic-operators.markdown
The logical next step after https://github.com/elixir-lang/elixir/pull/5142 :) \cc @josevalim, I opened a PR just to check that it's ok to point to `/docs/master` instead of `/docs/stable` since I assume the new page won't be in `/docs/stable` yet, right?
> Point to point to the "Operators" page in the Elixir docs

- getting-started/typespecs-and-behaviours.markdown
A link actually worked but wouldn't bring you directly to the Notes section which should be fixed by accepting this PR.
> Fix a broken link to Typedefs Notes section.

- _includes/mix-otp-preface.html
- getting-started/mix-otp/agent.markdown
- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/docs-tests-and-with.markdown
- getting-started/mix-otp/ets.markdown
- getting-started/mix-otp/genserver.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
In the beginning of every chapter reference the previous chapter and the first
chapter of the "OTP & Mix" guide.
See #834
I can change the wording if required.
> Mark "Mix & OTP" chapters as part of the guide

- getting-started/meta/macros.markdown
The name `options` for the second argument didn't seem to make much sense given that the implementation is `unless`. What do you think about renaming the variable to `expression`?
> Rename variable in `unless` example

- getting-started/basic-operators.markdown
based on 
https://github.com/elixir-lang/elixir/pull/5238/files#diff-50948d471af46f8f79bf8d175641fa42R67
by @fboyer
> Correct types in sorting order

- getting-started/mix-otp/task-and-gen-tcp.markdown
Function `serve` is an infinite loop itself, so recursive call to `loop_acceptor` is never reached, and thus unneeded.
> Remove unreachable line

- getting-started/mix-otp/task-and-gen-tcp.markdown
On a second thought, if we remove the line we should also remove line 180, and probably need to explain why we added `loop_acceptor(socket)` in line 190.
I recommend adding `loop_acceptor(socket)` back after line 53 and add a small note explaining why the line is there.
Maybe the note's wording does not match the writing style, so please fill free to change it as you wish.
> Add unreachable line back plus a note

- getting-started/mix-otp/task-and-gen-tcp.markdown
Amends changes made in PR https://github.com/elixir-lang/elixir-lang.github.com/pull/851. The tail call to `loop_acceptor/1` should go at the end of `loop_acceptor/1`.
> Fix call to loop_acceptor

- getting-started/binaries-strings-and-char-lists.markdown
- getting-started/erlang-libraries.markdown
Hi!
As far as I understand `to_char_list` is deprecated. I am renaming it to `to_charlist`
> Rename to_char_list to to_charlist

- getting-started/structs.markdown
There was no mention of not passing default values or requiring some fields to be passed a value.
> Default values and required values

- getting-started/mix-otp/agent.markdown
Just some simple improvements for readability.
- Clear up paragraph on async tests and race conditions.
- Add a few missing words and reword intro passage to make it a bit briefer.
- Change "ExUnit Callbacks" section title to mention test setup.
> Improve readability in mix-otp/agent.markdown

- getting-started/mix-otp/docs-tests-and-with.markdown
When introducing `with`, explain briefly how the construct can replace
nested `case` clauses.
Additionally, fix a typo referring to KVServer.
> Amend explanation of `with` construct in mix-otp guide

- getting-started/basic-types.markdown
- getting-started/introduction.markdown
- index.html
This patch has assorted edits.
**Oxford comma:** We commented a few days ago with @josevalim that the docs do not use the Oxford comma consistently. It is one of those style details that are worth having uniform across the docs and you need to pick one option and stick to it. Going with the Oxford comma seems to be the safest choice because [a majority of style guides](https://en.wikipedia.org/wiki/Serial_comma) of American English mandate its use.
**Error message of `hd []`:** Completes the output to match the real one.
**`size` vs `length`:** There is a mnemonic to easily remember which of `size` or `length` mean "linear".
**First `iex` session:** The first `iex` session the reader finds has one partial banner. Since this is the first time a session like this is shown I believe readers …
> Assorted edits

- getting-started/case-cond-and-if.markdown
Statement appears to be in conflict with Getting Started Guide, [Basic Operators](https://github.com/elixir-lang/elixir-lang.github.com/edit/master/getting-started/basic-operators.markdown) where on line 44 it says.
````
`or` and `and` are short-circuit operators.
````
I removed `short-circuit` when describing `&&`, `||` and `!` usage in guard clauses.
> Correction to case-cond-and-if Getting Started

- getting-started/basic-operators.markdown
- getting-started/binaries-strings-and-char-lists.markdown
- getting-started/case-cond-and-if.markdown
More edits:
* Oxford comma in a few places.
* Removes `:erlang.hd(1)` according to https://github.com/elixir-lang/elixir-lang.github.com/pull/875#issuecomment-260584786.
* A missing space.
* The patch changes **keyword list** to _keyword list_ because in previous sections new technical terms go in italics, like _pin operator_. Also, using italics when vocabulary is first introduced is a pretty standard convention (so no need to change the previous ones to bold face, going with italics is fine).
* I have reworded the explanation about why does `is_number(if true)` fail. The current description says Elixir tries to invoke `is_number/1`. I don't know the internals, but from a user's perspective I think the idea is that Elixir is going to look for a function with the arity parsed at the call …
> More assorted edits

- getting-started/binaries-strings-and-char-lists.markdown
This patch revises the usage of the term "code point" in the section of the Getting Started guide about strings.
In Unicode terminology, a _code point_ [is an integer](http://unicode.org/glossary/#code_point), and the glyph is a _character_, so the wording needs to be precise in that sense: Say "code point" to refer to the code, and say "character" when you are talking about its visual representation.
Similarly, make crystal clear to the reader that a char list is a list of integers that satisfy some ad-hoc condition, and that single-quoted literals allow you to create such lists.
> Revises Unicode terminology

- install.markdown
Since Fedora 22 they switched from yum to dnf tool.
More: https://fedoraproject.org/wiki/F22_release_announcement#Faster_and_better_dependency_management_with_DNF
> Update install section about Fedora and dnf

- getting-started/modules.markdown
The "concat.ex:7" bit goes now below the warning, indented as backtrace:
```
warning: this clause cannot match because a previous clause at line 2 always matches
concat.ex:7
```
> Updates the output of an example

- getting-started/protocols.markdown
There appears to be a minor typo in the protocols guide.
> Fixed typo: Extra code fencing near the list of data types.

- getting-started/protocols.markdown
Just started learning today, but fairly sure that should be a Module and not a Protocol.
> Fixes typo in Protocols section of getting started

- getting-started/processes.markdown
The main contribution in this patch is explaining that `send/2` does not block. This is an introduction to processes, and the text says that `receive` waits. People new to the language would naturally wonder at that point if senders wait for their message to be consumed by the recipient.
The rest are details here and there seen on passing.
> Edits in processes.markdown

- getting-started/protocols.markdown
Implementing the protocol for `Binary` does not work with strings. Instead we need to implement it for `BitString` in 1.3.4.
I guess this should be fixed (hopefully soon) as it is related to the code, not just the documentation or error messages. Please correct me, if i got it wrong.
> Implement protocol for BitString to make it work for strings

- getting-started/basic-types.markdown
> Fix typo in the Getting Started guide

- getting-started/comprehensions.markdown
It's a small thing, but because this is the first example with multiple generators in comprehension for some reason it confused me a bit more than it should have, and I think it makes it easier to read the first time around if ``dirs`` are explicitly set.
> Comprehension example a bit clearer by providing ``dirs``

- getting-started/mix-otp/genserver.markdown
As I read through the genserver getting started guide I found myself mentally editing and rearranging the prose a little bit. In particular, as a complete beginner, I was confused as to why the create operation was implemented as a cast, only to discovered towards the bottom of the document that it was only for illustrative purposes.
In any case, here are my suggestions.
> Edits to genserver getting started guide for clarity.

- getting-started/mix-otp/supervisor-and-application.markdown
- getting-started/modules.markdown
- getting-started/pattern-matching.markdown
This commit also closes correctly the `img` tag element in the "Supervisor and Application" lesson.
> Fix end of fenced code blocks

- getting-started/io-and-the-file-system.markdown
Just minor edits of things I saw reading this chapter:
* The sections about `File` and `Path` link their corresponding module in the opening paragraph, but the one about `IO` does not. Just unify this.
* The part about `File.read!/1` only covers the difference with regards to errors. I think it makes sense to explain the whole thing for completeness. In addition, the rewording deliberately uses a vague statement about error conditions, to imply you get an error if the file does not exist, but also if the user does not have read permissions, file descriptors limit is reached, or cosmic rays are doing cosmic things :).
* Details.
> Edits in the "IO and the file system" chapter

- index.html
I kept getting this warning in iex:
`warning: crypto:md5/1 is deprecated and will be removed in a future release; use crypto:hash/2`
The documentation on the front page uses `crypto.md5`. I changed this in favour of `crypto.hash`.
> Replace deprecated :crypto.md5 call with :crypto.hash(:md5, str)

- getting-started/alias-require-and-import.markdown
Besides the details like the Oxford comma and such, the main edit in this patch rewords a bit the introduction of `alias`.
The original example has a complete module definition
```elixir
defmodule Math do
alias Math.List, as: List
end
```
and the text starts saying
> From now on, any reference to `List` will automatically expand to `Math.List`.
If you look at the two, you'll see "From now on" is not as clear as it could be, because there is not even a place in which the alias is effective. The text introduces `alias` with an example in which the directive has no effect. Moreover, at this point the reader does not know `alias` has lexical scope, so they could wrongly believe that maybe "From now on" has a wider scope.
In addition to that, if `Math.List` was implemented within `Math`, then …
> Edits in the "alias, require, and import" chapter

- getting-started/sigils.markdown
Edits that need some explanation:
* The reason for alternative delimiters is explained with a slightly different emphasis. Point is to be able to write literals that read literally, to avoid escaping delimiters. For example, contrary to what the text says, parentheses for regular expressions are fine as long as the literal has no parentheses.
* In "Strings, char lists and words sigils", "words" becomes "word lists" to match the subsection title. In particular, in the TOC they read next to each other.
* When introducing `~s`, there is no point in mentioning single quotes. You want to change the delimiter if double quotes are present. Presence of single quotes is irrelevant.
* Regarding escape codes, I think `\"` and `\n` belong to different categories. You may leverage that part to talk …
> Edits in sigils.md

- getting-started/erlang-libraries.markdown
- getting-started/typespecs-and-behaviours.markdown
- getting-started/where-to-go-next.markdown
I have completed the getting started guide, here's a last patch with minor details.
Things that deserve a comment:
* When I read the paragraph that says that the digraph API modifies the graph in-place I wondered what is this vodoo :). Given this API is like nothing you've seen before, I believe a short explanation would leave the reader less puzzled. I have reordered the exposition to come after the shell session, and leveraged that ETS comes next to explain and connect in one shot.
* "ZIP" is the most common spelling I'd say. For example look at its [MIME registration](http://www.iana.org/assignments/media-types/application/zip). [Wikipedia uses ".ZIP"](https://en.wikipedia.org/wiki/Zip_(file_format)), with a leading dot, but in any case you do not write "zip files" normally. Different …
> Final minor details

- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/introduction-to-mix.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
Mix 1.4 introduced automatic inference of required applications from
dependencies list. Now Mix creates `:extra_applications` instead of
`:applications` by default in application configuration in `mix.exs`.
This commit updates the example `mix.exs` configurations in the guide to
reflect that change.
Signed-off-by: Bonghyun Kim <bonghyun.d.kim@gmail.com>
> Update mix.exs of guide to use :extra_applications

- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/docs-tests-and-with.markdown
- getting-started/mix-otp/ets.markdown
- getting-started/mix-otp/genserver.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
Reflect new application directory structure from `mix new MyApp --sup`
in Mix 1.4.
Add parentheses to function calls used like variable, like `self()`,
`table()`, `flush()`.
Change a few wordings for better clarity.
Other minor changes like the result of `Task.async`.
Signed-off-by: Bonghyun Kim <bonghyun.d.kim@gmail.com>
> Update Mix and OTP guide for Elixir 1.4

- install.markdown
Came across Issue #873 and thought the suggestion for adding documentation for Raspberry Pi would be useful. I just used it myself.  Also, noticed the Issue has been dormant for a few months so thought to pick it up.
The erlang download is especially useful.
Closes #873
> Installation for Raspberry Pi

- getting-started/introduction.markdown
- getting-started/mix-otp/introduction-to-mix.markdown
- install.markdown
Based on the discussion [here](https://github.com/elixir-lang/elixir-lang.github.com/issues/924) we're also renaming the preferred way to find one's currently installed Elixir version.
> Specify elixir version in appropriate places

- _data/elixir-versions.yml
- docs.markdown
- install.markdown
based on chages proposed in https://github.com/elixir-lang/elixir-lang.github.com/pull/931
Link directly to latest version compressed files in Install page
- stable Precompiled.zip
- stable source code (zip and tar.gz)
> Link directly to latest version compressed files in Install page

- _data/elixir-versions.yml
- docs.markdown
2nd try for https://github.com/elixir-lang/elixir-lang.github.com/pull/930
- We keep all the latest versions in one file, so we don't need to update them many places.
- Additionally it adds links to the Elixir v1.0 docs
- Adds links to Docs.zip in Stable version
> Keep latest Elixir versions in a data file (2nd try)

- getting-started/basic-operators.markdown
Since 1.4 it will raise BadBooleanError instead of ArgumentError. 
See the following links:
- https://github.com/elixir-lang/elixir/releases/tag/v1.4.0
- https://github.com/elixir-lang/elixir/commit/6b8db410b33b3cc77a5bab07c709eed9b4bcc564
> Providing a non-boolean will raise a BadBooleanError

- getting-started/keywords-and-maps.markdown
This doc implies that the pipe syntax for updating a Map (like so: `%{map | :a => 3}`) only works for atom keys, but it actually can be used for any key type.  The PR updates the doc to reflect that.  I also added an example usage of `Map.put` to the section on the Map module's functions, because adding a new key/value seemed like one of the more fundamental things someone would wonder how to do.
> updated Maps section

- _data/getting-started.yml
- getting-started/basic-types.markdown
- getting-started/introduction.markdown
- getting-started/mix-otp/agent.markdown
- getting-started/modules-and-functions.markdown
- getting-started/modules.markdown
Some users were finding it difficult to know where functions page of the
getting started guide was at a glance. Renaming it to "Modules and
Functions" helps to clarify this.
Only the title of the page has been changed so that the URL remains
unchanged.
> rename "Modules" page to "Modules and Functions"

- getting-started/mix-otp/supervisor-and-application.markdown
This change solves the race problem.
It makes sure the reference is made before the process dies.
> updated test case

- getting-started/mix-otp/agent.markdown
Added a space to a function in a code example. The formatting was inconsistent compared to the other examples on this page. I believe this to be a typo.
> agent.markdown

- index.html
The first comments said "spawns an Elixir process...", the second said "Block until..."
I feel it should be "spawn" and "block" or "spawns" and "blocks"
> Make comments more consistent

- install.markdown
My change was to the spelling in the Docker section but my linter picked up a few whitespaces/retuns that it cleaned up
> updated spelling in docker section of distibutions

- getting-started/try-catch-and-rescue.markdown
Correct an error in the description of the try/catch/else statement in the guide.
> Correctly describe `else` behaviour in try/catch guide

- _includes/search.html
- _includes/top.html
- _posts/2016-07-14-announcing-genstage.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
I saw the Tweet referencing some errors in the report from Rocket Validator.
Tweet: https://twitter.com/rocketvalidator/status/842073375514210312
Report: https://rocketvalidator.com/s/a1508cd6-02d1-4129-b8e8-4e0a7df109b5/p
It looks like the majority of those are repeats from include files. I think this should clean up most of them. I'll point out that the `lang` attribute on the `html` element may not be a good idea if you guys have or plan to roll out translations into other languages while reusing the same `top.html` include.
> Rocket validator

- learning.markdown
Old bit.ly url redirects to https://bigmachine.io/products/take-off-with-elixir-all-of-it?utm_source=elixirlang&utm_medium=banner&utm_campaign=elixir_lang_learning which is 404 right now.
> Change "Take Off With Elixir" url in learning section

- getting-started/mix-otp/agent.markdown
I might be mistaken, but the term 'dictionary' seems more appropriate when discussing the relevant Python data structure, while 'keyword list' was returned when performing the following in Iex:
```elixir
{a, b} = {:ok, bucket: "bucket"}
{:ok, [bucket: "bucket"]}
i b
Term
[bucket: "bucket"]
Data type
List
Description
This is what is referred to as a "keyword list". A keyword list is a list
of two-element tuples where the first element of each tuple is an atom.
Reference modules
Keyword, List
Implemented protocols
Collectable, Enumerable, IEx.Info, Inspect, List.Chars, String.Chars
```
> Replace the term 'dictionary' with 'keyword list'

- getting-started/introduction.markdown
The tutorial says the minimum requirement of elixir is `1.4.0` and again it says when you enter `iex`  in the terminal, the terminal shows erlang and elixir versions, but in this case(in the docs) it is showing `1.3.4`, which does not met the minimum requirement. So it must at least `1.4.0`. It's good for beginners.
> Update elixir version to 1.4.0

- getting-started/case-cond-and-if.markdown
The case statement contained an extra space that is not present in any of the other examples.
> Removes extra space in case statement

- _includes/top.html
- _posts/2016-07-14-announcing-genstage.markdown
- css/style.css
This PR fixes some HTML issues catched in [this report](https://rocketvalidator.com/s/6a76528d-23a1-48b0-b8f8-9f692bc7a626/i):
* H1 should be used for top-level headings (not for the logo).
* frameborder attribute is obsolete, use CSS instead.
> Fix HTML issues

- getting-started/processes.markdown
Put "inspect" between "`" and "`".
> Minor fix in processes.markdown

- getting-started/alias-require-and-import.markdown
This edit syncs the Getting Started guide with https://github.com/elixir-lang/elixir/pull/6041.
To summarize the rationale here: If module `M` wants to use macros from `N`, it needs to require `N` **regardless** of whether `N` is loaded in the VM (see example in the PR linked above). Therefore, ensuring the module is loaded is not really the purpose of `require`, you may have the module loaded and still not be able to access its macros.
That is because `require N` actually adds `N` to a list of modules required by `M`, and being in that list is what controls their visibility. Additionally, the compiler needs to load `N` in order to expand its macros if used, but that is more of an implementation detail.
By removing emphasis on the compilation and loading of the required module, the …
> Changes focus in the require explanation

- _includes/top.html
Currently the Google fonts link uses `http:`, even when on a secure URL, this causes the font to not be loaded when on a secure URL.  Currently the primary site 'works around' this by having Cloudflare perform URL rewriting, which hides it, however this does not fix mirrors that use direct hosting.  This commit fixes this by allowing the browser to use http or https as necessary as was done with the analytics javascript link earlier, this should complete the work.
> Fix Secure font loading

- getting-started/mix-otp/task-and-gen-tcp.markdown
On line `221` it is proposed how to start the application with a default port. However, on line `245`when the application is run again, it does not include how to configure the port when calling `mix run --no-halt`.  I suggest updating the command to `PORT=4040 mix run --no-halt`, if that is an adequate solution.
> Add instruction to run command with additional arg

- getting-started/typespecs-and-behaviours.markdown
An alternative way to fix the grammar would be to change the word "wrote" to "write", instead of changing the word "if" to "though".
> Grammer fix in "Static code analysis" section

- _posts/2017-07-25-elixir-v1-5-0-released.markdown
I just saw Elixir 1.5 announcement, and the use of asciinema in the post. Awesome!
I noticed that you spelled it "asciicinema" instead of "asciinema", so here's a quick fix.
> Fix asciinema spelling

- getting-started/mix-otp/task-and-gen-tcp.markdown
Closes #1002 
also changes a reference from `init/1` to `start/2`
> Remove inconsistent reference to fault tolerance from Tasks and gen_tcp chapter (#1002)

- getting-started/binaries-strings-and-char-lists.markdown
I'm learning Elixir at the moment, so I apologize if I've overlooked something, but this is what I've found:
Elixir 1.5.0
iex> String.valid?(<<239, 191, 191>>
true
Elixir 1.4.0
iex> String.valid?(<<239, 191, 191>>
false
I'm not sure if the documentation should be updated to reflect the new behaviour of String.valid? or if the function is not working the way it was intended to. At this point, I've assumed the documentation needs to be updated to the new behaviour so I just tweaked the byte sequence to be an invalid string.
Any thoughts?
> Invalid string (byte sequence) is no longer false.

- crash-course.markdown
What were proposed in this Pull Request ?
* Given example were confused to readers that 'lists:map(fun math:square/1, [1, 2, 3]).' could be part of .erl file or it could be executed separately or entirely code block executed at erlang shell.
* I believe to make simplification is better in the community so i made code more readable and simple.
Requesting reviewers to review and if looks good merge it.
> Implemented readability of code at crash course at Elixir-lang

- getting-started/mix-otp/introduction-to-mix.markdown
Since the code example uses [`Mix.env/0`](https://hexdocs.pm/mix/Mix.html#env/0) (instead of [`Mix.env/1`](https://hexdocs.pm/mix/Mix.html#env/1)), I think it makes more sense to link to `Mix.env/0`.
> Link to Mix.env/0 instead of Mix.env/1

- getting-started/pattern-matching.markdown
What were proposed in this Pull Request ?
iex> length([1, [2], 3]) = 3
above syntax won't give below error
** (CompileError) iex:1: illegal pattern
but it gives ** (CompileError) iex:1: cannot invoke remote function :erlang.length/1 inside match
so it has been manually verified at shell and update the documentation.
> Wrong Error exception issue at documentation fixed

- getting-started/alias-require-and-import.markdown
- getting-started/basic-types.markdown
- getting-started/case-cond-and-if.markdown
- getting-started/comprehensions.markdown
- getting-started/enumerables-and-streams.markdown
- getting-started/erlang-libraries.markdown
- getting-started/introduction.markdown
- getting-started/io-and-the-file-system.markdown
- getting-started/meta/domain-specific-languages.markdown
- getting-started/meta/macros.markdown
- getting-started/meta/quote-and-unquote.markdown
- getting-started/mix-otp/agent.markdown
- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/docs-tests-and-with.markdown
- getting-started/mix-otp/dynamic-supervisor.markdown
- getting-started/mix-otp/ets.markdown
- getting-started/mix-otp/genserver.markdown
- getting-started/mix-otp/introduction-to-mix.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
- getting-started/module-attributes.markdown
- getting-started/protocols.markdown
- getting-started/sigils.markdown
- getting-started/try-catch-and-rescue.markdown
Found these while going through the Guide. I might have missed some, but it's a start. 😄
> Fix grammar and typos in the Guide

- getting-started/mix-otp/docs-tests-and-with.markdown
Remove 'in' on line 60 in the getting started doctest guide to clarify grammar for explanation of doctest format.
> Remove a word in doctest guide for a minor grammatical fix

- install.markdown
* Ubuntu Precise (12.04) has reached EOL, removed from list.
* Added other Ubuntu and Debian versions with packages available on https://packages.erlang-solutions.com/erlang/
> [install.markdown] Update Ubuntu and Debian versions

- getting-started/basic-types.markdown
* The text mentioned prepending, while the code was concatenating two lists. The distinction between whether "prepending" or "appending" is fast depends on the size of the left-hand list.
* There exists explicit prepending to a list as well, which is constant time
This is pretty much migrating some content from https://hexdocs.pm/elixir/List.html.
> Re-word discussion of list prepend / append performance

- getting-started/meta/domain-specific-languages.markdown
Just removes the `warning: variable "env" is unused` message
> Remove unused "env" warning

- getting-started/mix-otp/dependencies-and-umbrella-apps.markdown
This change reflects the latest stable elixir version (1.5.1), after running `mix new kv_umbrella --umbrella` (maybe it is different upstream?).  
My first PR here, hope it's fine.
> Update mix.exs deps call

- getting-started/comprehensions.markdown
The last Pythagorean triples is missing numerous Pythagorean triples.  The filter "a + b + c <= n" looks like an accident in the application the triangle inequality.  The theorem actually states "a + b >= c."  Adjusting this will result in the inclusion of missing triples without duplication.
> Update Pathogrean Triples example (missing triples)

- getting-started/comprehensions.markdown
Nothing major, just removed a spurious `+` to make it work.
> Fix code typo introduced on ed4fb99

- getting-started/typespecs-and-behaviours.markdown
The original documentation was throwing an error because reason and value are not defined. Assuming reason is a string and the value is a term, the proposed changes at least compiles. This also matches the definition in line 145. I also added a note explaining what `term` represents.
Error:
```
** (CompileError) iex:2: type reason() undefined
(stdlib) lists.erl:1338: :lists.foreach/2
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6 
(iex) lib/iex/evaluator.ex:219: IEx.Evaluator.handle_eval/5
```
> Update typespecs-and-behaviours.markdown to remove compilation errors in the Parser definition

- getting-started/mix-otp/task-and-gen-tcp.markdown
Added a KVServer module definition to the file. Received this error without it:
`** (ArgumentError) cannot invoke def/2 outside module`
> Update task-and-gen-tcp.markdown to have KVServer module

- getting-started/basic-types.markdown
This PR is an attempt to be more explicit(via a wording fix) on the purpose each operator serves when used in the context of Lists in Elixir
> Modify wording on the usage of some operators in Lists to make it sound more accurate

- _posts/2017-10-31-stream-data-property-based-testing-and-data-generation-for-elixir.markdown
* Do we want to badge link as directly linking to a PDF (is this still good etiquette)?
* This looks like the correct paper from ICFP 2000, as the original link [from here](http://www.cse.chalmers.se/~rjmh/QuickCheck/) is broken.
> Fix missing link to QuickCheck paper

- _posts/2017-12-05-whats-new-in-elixir.markdown
The original blog posts says this
>We’d love to hear from you about what you’d like to see in future posts **so get join** the conversation (...)
which looks to be a typo. This fixes it.
> Fix typo in 2017-12-05 blog post

- getting-started/basic-types.markdown
"Aliases start in upper case *and* are also atoms"
> Add missing 'and'

- _config.yml
I've noticed that when I search for elixir, google points me to  https://elixir-lang.github.io instead of elixir-lang.org Looks like the canonical URL has not been set and it defaulted to GitHub one. This PR fixes it.
Before this canonical link looks like this (after GitHub build):
```
<link rel="canonical" href="http://elixir-lang.github.io/" />
```
After this PR it should be this:
```
<link rel="canonical" href="https://elixir-lang.org/" />
```
> Specify canonical URL in Jekyll config

- install.markdown
This PR fixes the typo of "Raspbian" being incorrectly spelled as "Raspian", and introduces a couple of minimal changes to the text to (hopefully) make it slightly more grammatically correct without altering the meaning of anything that's being said.
> Fix a typo and perform minimal touch-ups on text

- getting-started/mix-otp/supervisor-and-application.markdown
The next page actually covers Dynamic supervisors.
> Fix old reference to `simple_one_for_one`

- getting-started/mix-otp/dynamic-supervisor.markdown
The code in `KV.BucketSupervisor.start_bucket` is calling the `Supervisor.start_child` function when it should (probably) be calling the `DynamicSupervisor.start_child` function. I tried the code sample on my machine, and it fails with a function match error with the former call, but it runs ok with the latter.
> Fix typo in the code sample for DynamicSupervisors

- getting-started/mix-otp/introduction-to-mix.markdown
Minor change in how test results are shown (compared to actual output)
Pls note, I'm a complete git newbie so please tell me if I'm doing something I should not...
> Minor change in output

- learning.markdown
This PR changes the URL to the 2nd edition of Elixir in Action. The book is admittedly still in MEAP, but I think that at this point it's already better to point to the 2nd edition for the following reasons:
- the 2nd edition page contains the link to the 1st edition
- the buyers of the 2nd edition get the ebook version of the 1st edition included
- I wouldn't recommend buying the 1st edition anymore, since unfortunately Manning doesn't offer a free upgrade
> change Elixir in Action link to 2nd edition

- getting-started/mix-otp/docs-tests-and-with.markdown
Add explanation for functions without body when used as a way to document the arguments.
> Add explanation for functions without body

- getting-started/enumerables-and-streams.markdown
Since `Stream.cycle/1` calls `Stream.unfold/2` for a `list`, the message should be `Stream.unfold/2`.
> Fix message after Stream.cycle call on lists

- crash-course.markdown
Seems the cookbook is no more.
> Remove dead link to Erlang cookbook

- _data/getting-started.yml
- getting-started/mix-otp/dependencies-and-umbrella-projects.markdown
Minor details I've seen while reading this guide.
Two highlights:
* The title in the TOC is out of sync with the title in the Markdown file. The TOC says "Dependencies and umbrella apps", and the guide says "Dependencies and umbrella projects" (see the [current guide](https://elixir-lang.org/getting-started/mix-otp/dependencies-and-umbrella-apps.html)). I have updated the TOC and filename. If this should be the other way around or something has to be done to get a redirection on the previous slug please just tell me :).
* "git" -> "Git" in a few places. The SCM is Git, and `git` a command-line executable. Similar to Elixir and `elixir`.
The rest are self-explanatory.
> Edit pass in the umbrellas guide

- getting-started/modules-and-functions.markdown
I propose to add short explanation about naming conventions in the "Modules and functions" chapter.
I feel introducing these (namely, trailing question mark and leading underscore) is a bit confusing, and telling the reader that it's just naming conventions should reassure them.
> Adding explanation about the naming conventions

- _includes/important-links.html
- _includes/try-elixir.html
- _layouts/getting-started.html
- css/style.css
- learning.markdown
This commit removes links to Code School's Try Elixir course in advance of codeschool.com shutting down on June 1, 2018.
> remove Try Elixir learning resource links

- getting-started/mix-otp/ets.markdown
The type of table identifiers changed from integer to reference in OTP20, according to the changelog : http://erlang.org/download/otp_src_20.0.readme
I edited the first snippet where `:ets.new/2` was returning an integer, so as to have it return a reference.
I was pointed toward the document thanks to this answer on StackOverflow: https://stackoverflow.com/a/49633326/7051394
> Updated the output of `:ets.new/2` in ETS documentation

- getting-started/pattern-matching.markdown
Calling `_` in iex returns a CompileError noting invalid use of `_` instead of an unbound variable error.
> Wrong Error exception in Pattern Matching doc

- getting-started/typespecs-and-behaviours.markdown
The example modules JSONParser and YAMLParser on the "Adopting behaviours" examples would not compile ( "(ArgumentError) cannot invoke def/2 inside function/macro" ) if the parse function does not return anything. By adding a simple empty string we allow a beginner to copy the code and see the expected behaviour. The thing that matters in these example is for the reader to experiment with leaving out a Parser callback and witness the behaviour warning, not having to figure out a compilation error at the time he is learning.
> Minor add to "Adopting behaviours" examples

- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/docs-tests-and-with.markdown
- getting-started/mix-otp/dynamic-supervisor.markdown
- getting-started/mix-otp/genserver.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
Hello!
I've re-read the articles for OTP, and noticed the code is still formatted "the old way". I've spent some time to re-format it the way it would be left by `mix format`.
Hope that helps!
> Formatting

- getting-started/mix-otp/introduction-to-mix.markdown
There is a bug referencing the wrong repo in one instance.  Added three references to make it easier for readers of the documentation.
> Fix a documentation bug, and add 3 reference links

- getting-started/introduction.markdown
- getting-started/meta/macros.markdown
- getting-started/mix-otp/agent.markdown
- getting-started/mix-otp/dependencies-and-umbrella-projects.markdown
- getting-started/mix-otp/distributed-tasks-and-configuration.markdown
- getting-started/mix-otp/docs-tests-and-with.markdown
- getting-started/mix-otp/ets.markdown
- getting-started/mix-otp/introduction-to-mix.markdown
- getting-started/mix-otp/task-and-gen-tcp.markdown
- getting-started/module-attributes.markdown
- getting-started/modules-and-functions.markdown
- getting-started/recursion.markdown
- getting-started/where-to-go-next.markdown
`bash` denotes a shell script whereas `console` denotes a shell session.
Basic examples don’t look very different (before first, after second):
One benefit is that Bash keywords are no longer highlighted (`for` in this case):
The only downside I could find is that comments in the output are no longer highlighted:
However, for the sake of consistency, I’ve changed them to `console` as well.
> Use `console` language for command line examples in guides

- getting-started/mix-otp/task-and-gen-tcp.markdown
`start_link/3` was changed to `start_link/1` in https://github.com/elixir-lang/elixir-lang.github.com/commit/cb0987997be2b463399510c6b690f7ed52913168. Therefore, it doesn’t really make sense to refer to `start_link/3` and to re-explain that `start_link/1` receives an anonymous function.
> Fix guide reintroducing `Task.start_link/1`

- getting-started/introduction.markdown
Add example of using iex -S mix compile
> Add example of using iex -S mix compile

- getting-started/basic-operators.markdown
- getting-started/case-cond-and-if.markdown
- getting-started/io-and-the-file-system.markdown
Following links in corresponding pages were fixed:
* Basic operators page; operators documentation link
* case, cond and if page; guards documentation link
* IO and the file system page; IO documentation link
> Fix dead links in Getting Started guide

- getting-started/binaries-strings-and-char-lists.markdown
commit 786d32ecc99ece297e4171e914e695408a969fde contributed information
regarding binary and char list concatenation but it resulted in a
paragraph referring to a previous example being pushed into the wrong
place.
This patch fixes this issue.
> binaries-strings-and-char-lists - fix misplaced paragraph

- getting-started/mix-otp/dependencies-and-umbrella-projects.markdown
It was unclear what was meant by different configuration for different applications. It makes more sense to say "where you want to use different configurations in each application for the same dependency" as it's clear the different configuration is for the same dependency.
> Clarify sentence on configuration limitations in umbrella apps

- getting-started/mix-otp/task-and-gen-tcp.markdown
Emphasizing the use of an environment variable for the server port in “Task and gen_tcp” guide.
Changes related to this [issue](https://github.com/elixir-lang/elixir-lang.github.com/issues/1132).
> Emphasize PORT as environment variable in “Task and gen_tcp” guide

- getting-started/debugging.markdown
Fixing link in the debugging section:
> We explore the Observer in the context of an actual project in the [in the Dynamic Supervisor chapter of the Mix & OTP guide](https://elixir-lang.org/getting-started/mix-otp/dynamic-supervisor.html).
Has now a link to the [right section](https://elixir-lang.org/getting-started/mix-otp/dynamic-supervisor.html).
Changes related to this [issue](https://github.com/elixir-lang/elixir-lang.github.com/issues/1144).
> Fix Dynamic Supervisor link in the debugging section

- getting-started/typespecs-and-behaviours.markdown
To conform to the typespec in the Parser behaviour, the two parse functions in the implementations in JSONParser and YAMLParser should return a tuple. This makes the example executable as is.
> Make Dynamic Dispatch example executable.

- getting-started/modules-and-functions.markdown
Functions like these are used in example factories for thoughtbot/ex_machina
> Show string-building anonymous function without parens

- _data/getting-started.yml
**Reason:** Put the title with the oxford comma, as in the title of the page.
> fix / the titles without the oxford comma in the side menu

- getting-started/io-and-the-file-system.markdown
**Reason:** Put the link label the same as the page title. And remove the space from `charlists`.
> fix / the link label

- getting-started/debugging.markdown
changed from a phrase using the mis-matched pronouns "one" and "their" to a rephrasing without any such pronouns.
> rephrasing to avoid mis-matched pronouns.

- getting-started/debugging.markdown
changed from the possessive pronoun "their", in "their own tools", referring to the tools of "the community", to the possessive pronoun "its", since "the community" is a single entity. 
if "the community" is to be considered as being plural, please consider changing from "has also created" to "have also created".
> change pronoun to match number, of "the community"

- getting-started/typespecs-and-behaviours.markdown
Change a link to point to the section renamed by https://github.com/elixir-lang/elixir/commit/db017e7f18b35d69a2b4305efc0f002bb3675669.
> Fix outdated link to `String.t` typespec note

- _data/elixir-versions.yml
Link pointed to 1.6 as latest stable, but latest stable is 1.7.
**NOTE:** I am unable to test this commit, because I cannot install the development tools. The gems include nokogiri, which cannot be installed because of this problem: https://github.com/sparklemotion/nokogiri/issues/1772
But I think this should work. :P
> Fix wrong stable version leading to wrong download links

- getting-started/try-catch-and-rescue.markdown
Hello,
We are now translating this guide into Japanese on the https://github.com/elixir-lang-jp/elixir-lang.github.com repository.
Then I found some non backquoted word at "try, catch, and rescue" section.
Could you review this?
Thanks 😄
> Wrap by backquote

- getting-started/mix-otp/dynamic-supervisor.markdown
The previous instructions tripped me up a little: First, I created a new module `KV.BucketSupervisor` with the `init` function from the guide. My mind kept auto-correcting "in `lib/kv/supervisor.ex`" to "in `lib/kv/bucketsupervisor.ex`" ;)
After I found #1084, I replaced the whole content of the `KV.Supervisor` module, due to the instructions saying
> Note this time we didn’t have to define a separate module that invokes use DynamicSupervisor
this results in `(UndefinedFunctionError) function KV.Supervisor.start_link/1 is undefined or private`.
Then I finally got it right ;)
> Refine DynamicSupervisor instructions in Mix/OTP Guide

- getting-started/meta/macros.markdown
Additionally, because the variable is called before and after the macro.
Tracing how the value changes is easier to implement. 
```elixir
def go do
require Hygiene
a = 13
a
Hygiene.interference
a
end
```
Can easily be modified to log the values:
```elixir
def go do
require Hygiene
a = 13
a |> IO.inspect 
Hygiene.interference
a |> IO.inspect 
end
```
Without changing the end result.
This page helped a lot with my macro learning 👍 
The warning was the semi confusing part because it brings uncertainty to whether the original value is unused or the overriding value is unused. If this warning was intentional including the reasoning for the warning could be an alternative solution for the problem.
> fixes, warning: variable "a" is unused.

- getting-started/io-and-the-file-system.markdown
"a list of integers representing bytes or binaries" compared to "a list of characters or strings" in two adjacent paragraphs is slightly jarring. Changing both to "or" makes the comparison/transition easier to read.
> Harmonize the wording of two sentences

- getting-started/processes.markdown
I think the initial intent was to write "not unlike", but the "not" got dropped.
> Fix a statement about the heaviness of threads in other programming languages

- getting-started/debugging.markdown
Without the comma the sentence reads like "the last thing you will ever need to remember" versus "as the last thing in this section to do is remember this".
> Add a comma

- getting-started/basic-operators.markdown
Line 81 had an [Oxford comma](https://en.wikipedia.org/wiki/Serial_comma), but the rest of the document does not use Oxford commas.
The comma on line 112 would be better with a semicolon: it's delimiting two related clauses that *could* stand on their own and so should be connected with a semicolon rather than a comma.
> Add a semicolon, remove Oxford comma

- getting-started/mix-otp/genserver.markdown
It doesn't seem to be covered or used anywhere in the entire Getting Started guide, so its sudden use is a bit jarring.
Also add some code literal markup in one place.
> Don't use assignment pattern matching in function parameters

- install.markdown
The current URL for exenv on the installation page (https://github.com/mururu/exenv/) points to a project the appears to be dead. There are open pull requests dating back to 2014. A [discussion thread](https://github.com/mururu/exenv/issues/15) started in 2016 points to [this](https://github.com/exenv/exenv) repository as an actively-maintained alternative.
This pull request modifies the URL to point to the active project.
> Update exenv URL

- getting-started/structs.markdown
If you follow the tutorial in a `.ex` or `.exs` file, then referring to a struct leads to an unexpected error about it not being defined. (This has already come up on Stack Overflow: https://stackoverflow.com/questions/39576209/elixir-cannot-access-struct.)
> Add a note about being in a defmodule to refer to a struct

- getting-started/meta/macros.markdown
> Fix arity of alias!/1

- getting-started/basic-types.markdown
A minor fix in `Basic Types` section, which encloses the function arity in code block.
> Minor fix - enclose function arity in code block

- getting-started/io-and-the-file-system.markdown
@tsloughter mentioned on Slack this guide has less idiomatic Elixir examples (no parens in function calls), so I made a PR to consider adding them
> add parens as it's idiomatic

- _data/getting-started.yml
The title appeared in the table of contents as "Keywords lists and
maps" (note the "s" at the end of "Keyword"), but on the page it
appeared as "Keyword lists and maps". The table of contents version
was incorrect and has been changed.
> Fix section title "Keyword lists and maps"

- css/style.css
This PR brings back styling for outline when an element is focused. This is tremendously important for accessibility: http://www.outlinenone.com/
> Bring back outline styles

- install.markdown
repo was picked-up in wrong way because the Url logic.
So an user could endup to install wrong pkgs from elixir/erlang, which can led to bugs of incompatibility vs elixir and erlang version
when specified obs://devel:languages:erlang/ url, then zypper does look for current right distro version.
In this way each openSUSE distro has the right erlang/elixir pkgs.
> fix wrong url for opensuse distro obs://devel:languages:erlang/ url

- getting-started/mix-otp/dynamic-supervisor.markdown
Instructions were ambiguous, so wanted those to be specific. Included what the user should do with the DynamicSupervisor and where.
> The bucket supervisor; Improved instructions

- getting-started/mix-otp/dynamic-supervisor.markdown
On at least some linux distributions, the headless version of erlang is installed as the default dependency for elixir. This results in an error when trying to start the observer or other gui tools.
```elixir
iex> :observer.start
{:error,
{{:load_driver, 'No driver found'},
[...]
}}
```
> Adding note about headless vs gui-enabled erlang

- install.markdown
> In 2016, with the release of macOS 10.12 Sierra, the name was changed from OS X to macOS. ([source](https://en.wikipedia.org/wiki/MacOS#macOS))
> Rename "Mac OS X" to "macOS" in the installation doc

- install.markdown
As it was commented here (https://github.com/elixir-lang/elixir/issues/8990). Add Ubuntu 19.04 at the list of supported distros.
> Add ubuntu 19.04 to the list of supported distros

- getting-started/basic-operators.markdown
The original text makes it sound like you need a 'true' or 'false' literal on the left side.
> Clarify boolean operator rule

- _includes/important-links.html
I placed it above the link to ElixirConf US as the Code Elixir LDN conference will take place sooner than ElixirConf.
Also, the image graphic is included in the anchor tag such that the link is only present once, which should be good for both people navigating the site using keyboard and screen readers.
> Added a link to the Code Elixir LDN conference to important links

- getting-started/case-cond-and-if.markdown
Ran into an issue today, and when reading the docs I got the impression cond
looked specifically for `true`, and not just any truthy value.
> Clarify that cond conditions can return any truthy value, not just `true`

- getting-started/basic-types.markdown
would I have not missed it if it was more prominent, like I'm suggesting here?  I had reached the module attributes page, and finally realized there was a help function, so I said to myself let's put it somewhere in the text, where it should be introduced, and guess what I intended to put it just only one paragraph above the spot I had missed.
> I had totally missed the text in the note

- getting-started/basic-types.markdown
coming from Python, this assertion had me confused, until I reached the `&` operator for named functions in "chapter 8".
I think it's better to first show anonymous functions by themselves, not matched to a variable, then to do that match, and to avoid the contradiction in terms 'named anonymous'.
> *anonymous* functions first class citizens

- getting-started/mix-otp/agent.markdown
- getting-started/mix-otp/genserver.markdown
I was a bit overwhelmed when the `getting started` guide reached the use of `Agent` and even more so when it was the time for `GenServer`.  I added an example of plain straight use of Agent, which helped me make sense of writing and testing the KV.Bucket API.  I later saw this is precisely the approach taken in the https://hexdocs.pm/elixir/GenServer.html linked page.  I can follow it better that way.
but now what, I mean, do we want the reader to jump to the other docs, read and understand, but with the chance they get lost in far deeper details?  or do we want to copy/adapt part of that text into this getting-started guide?  I still didn't reach the place where it handles supervisors.
> reviewing getting_started/GenServer

- getting-started/mix-otp/supervisor-and-application.markdown
if I execute this instruction, given the current status of the code, I do not get so many fields as here exemplified, I just get `id` and `start`.
> synchronizing with code

- getting-started/mix-otp/genserver.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
I was reorganizing the text at the end of the chapter, answering (proposing an answer) the the open question "if this is a bad idea, what would be the proper solution?".  and I realized I was not only closing the chapter, but also introducing supervisors, which I think is precisely the introduction I had missed to that chapter.
this is part of what I was writing, mixed with stuff I intend to remove.
This however has a major drawback: when our registry is notified about any unexpected crash, we have to program the whole reaction to the new situation, a more prevalent practice in We typically avoid creating new processes directly, instead, we delegate this responsibility to supervisors. 
As we'll see in the next chapter, supervisors rely on links and that explains why link-based APIs …
> introduce supervisors at the top of the supervisors chapter

- getting-started/mix-otp/supervisor-and-application.markdown
the module, the function, the definition file.
> different meanings of "application"

- getting-started/mix-otp/supervisor-and-application.markdown
I've altered where we first mention `logger` according to my understanding.
then, possibly one or two sections too far into the text, I realize there's questions to be posed and answered.  preferably by breaking things and showing what it is that we've been using, unaware of it.
> help me understand the mechanisms

- getting-started/mix-otp/dynamic-supervisor.markdown
I am not sure, but there's so many idioms associated to "to go", that I would rather not risk traps.
(go away === leave) ?
> replace went away with it -> also stopped

- getting-started/mix-otp/introduction-to-mix.markdown
I split one of the points (define a module, define a test case) into three: define a module that uses ExUnit.Case, use **two** of the injected macros.
> the 2 things to notice is 4 according to me

- getting-started/module-attributes.markdown
Thank you for providing a great Getting Started documentation!
I found that a code example in ["As temporary storage" section](https://elixir-lang.org/getting-started/module-attributes.html#as-temporary-storage) of "Module attributes" chapter calls `send(conn, 200, "ok")`. But, `plug` does not have `send/3`; `send_resp/3` should be used for this purpose.
https://hexdocs.pm/plug/1.8.2/search.html?q=send
> Use `Plug.Builder.send_resp/3` in a code example in Getting Started

- install.markdown
I've only been maintaining these SlackBuilds for 3 years now; might as well advertise 'em :)
Note that at the moment SlackBuilds.org does not have the latest versions of Erlang/Elixir (my bad), but I submitted those today, so they'll hopefully be approved and included in the next SBo update cycle.  The updated versions of the SlackBuild scripts can be found in [the GitHub repo I use for maintaining my SlackBuilds](https://github.com/YellowApple/slackbuilds).
> Add Slackware install instructions

- getting-started/mix-otp/dynamic-supervisor.markdown
- getting-started/mix-otp/genserver.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
I was going through the Supervisor tutorial (it’s fantastic! Thank you so much for that!) and noticed a few small inconsistencies along the way.
I made the following changes:
* Removed `extra_applications` from the `.app` file code - I checked on Elixir 1.8.1. and it's not there anymore... Correct me if I'm wrong, of course!
* Made variable naming consistent in the implementation of `handle_cast`. Sometimes the second element of the tuple that is returned from `KV.Bucket.start_link([])` was called `bucket` and sometimes `pid`. I changed it to `bucket`.
* Corrected minor typos
- "what happens when something fail?" --> "what happens with something fail`s`?"
- "because a certain condition has reached" --> "because a certain condition `w`as reached"
- "But how we can automatically start the …
> Supervisor section changes

- install.markdown
OpenBSD has been providing elixir packages since 0.5.0 so we might as well list it here.
> add installation instructions for OpenBSD

- getting-started/enumerables-and-streams.markdown
When going through the tutorial I noticed that when executing `stream = File.stream!("path/to/file")` it does not return a function like in the docs `#Function<18.16982430/2 in Stream.resource/3>`.
In the proposed change I have added what was returned by `iex`.
I am not sure if tha was a mistake. Please close the PR if the docs are correct.
> Update example in Enumerables and Streams docs

- _config.yml
If you navigate to [https://elixir-lang.org/js/toc/](https://elixir-lang.org/js/toc/), you can see that the
README for the jekyll-table-of-contents javascript library is displayed.
This probably does not belong on the Elixir language site.
Add the toc README to the list of files ignored during site build.
> fix: Remove the README page for jekyll-table-of-contents

- getting-started/mix-otp/ets.markdown
While playing with ETS I was getting a generic ArgumentError. I thought I'm passing the arguments to the `:ets.insert` incorrectly, while the real cause was the access setting of the ETS table. I did not this information anywhere on `elixing-lang.org` and I believe it should be here.
> Update ets.markdown with accessibility example

- getting-started/modules-and-functions.markdown
It's not a script, so it makes sense to use it that way too.
> The name of the file was mentioned that way before

- install.markdown
* Update `ubuntu` and `Debian` instructions to use `erlang-solutions_2.0_all.deb` as recommended on Erlang Solutions website
* Update `Raspbian` to reference `buster` since that is now the latest OS
> Update install.markdown for ubuntu and raspbian

- getting-started/pattern-matching.markdown
The code is assuming that x = 1 is declared and then match is checked.
For a new user it's not very clear. I read it for the first time (completely new to Elixir) and thought that 1 = x is the declaration.
> x=1 declaration not clear in pattern-match readme

- _includes/conferences.html
- _includes/important-links.html
Added in important links; over the community section.
I have made it such that it is easy to add and remove conferences from a list; I thought it would be best to order the conferences such that the most recent is at the top, and the template includes room for a logo, the location (city, country/state), and a little space to write some information about dates. Hopefully this will make it easy to add and remove conferences from the list.
> Add upcoming conferences section and add CodeBeam SF & ElixirConf EU

- _includes/conferences.html
It's obsolete and unnecessary as all images are set to `border: 0`
in style.css.
> Remove obsolete border attribute from <img>

- getting-started/module-attributes.markdown
Clarifies that functions in the same module as the attribute is defined in cannot be called as they are not compiled yet.
> doc: Clarify available functions in attribute definitions

- _posts/2020-01-27-elixir-v1-10-0-released.markdown
Fixes a tiny typo: environemnt -> environment
> Fix typo in 1.10 release post

- _includes/conferences.html
The image file for the ElixirConf EU logo in the upcoming conferences section had gone awol. I've updated the uri to one that will hopefully stay up *forever*!
> Update the URI to the ElixirConf EU logo

- getting-started/mix-otp/supervisor-and-application.markdown
I fixed a minor grammatical error in the Supervisor/Application guide. The issue was a run-on sentence. I split the run-on sentence into two complete sentences.
> Fix a run-on sentence in Supervisor/Application guide

- getting-started/mix-otp/task-and-gen-tcp.markdown
Very similar to #1172 which missed last rewrite part
that still raised error if env variable was not present.
So if someone were to just copy last part then in next section tests would fail when doing simple `mix test`.
> Fix inconsistency regarding default port env var

- getting-started/mix-otp/ets.markdown
In the ETS guide, the function is written as `call/3`, but when we fix the issue in code, we use `call/2`. This is also supported by other written references to `call/2`.
> Correct the Arity of 'call' in the ETS Guide

- getting-started/mix-otp/agent.markdown
When encountering Agents for the first time, it is not clear to the newcomer that they pass their state to anonymous functions in this way. This problem stumped me for a whole day yesterday, when I couldn't figure out what was going on with that `&1`. 
It finally made sense when someone on the ElixirForum gave me this crucial piece of information, that the Agent calls the anonymous function and passes its state to it via the placeholder argument `&1`. https://elixirforum.com/t/partially-applied-functions-and-placeholder-arguments/30535/10
Hopefully this small edit can save someone else the confusion.
> Clarify how agent passes state to anonymous func

- getting-started/mix-otp/introduction-to-mix.markdown
The section about protocol consolidation in the Getting Started guide seems to have been removed. Consider pointing to Protocol documentation that explains consolidation instead.
> Remove broken link to protocol consolidation

- getting-started/enumerables-and-streams.markdown
The `total_sum` variable is unnecessary for this example, and is not discussed in the text. Also, the example is later compared to an equivalent code snippet without the pipe operator. In the comparison code there's no `total_sum` so they are not exact equivalents, hence confusing. Lastly, the example already introduces a few new concepts, so it might be better to keep it simple. For these reasons, I think it's better to drop the `total_sum` variable.
> Simplify example in enumerables-and-streams.markdown

- css/style.css
I was following the guides and noticed the Debugging page has horizontal overflow on screens < 640px due to the images having a hardcoded width, so adding this CSS rule makes the images contained to the screen width, improving mobile UX.
You can see the problem is especially relevant on small mobile devices like the iPhone SE.
Before:
After:
> add {max-width: 100%} css rule to all img tags to improve mobile UX

- getting-started/mix-otp/distributed-tasks.markdown
This fixes an issue with the OTP guide which is best described in the issue itself.
https://github.com/elixir-lang/elixir-lang.github.com/issues/1387
> MIX/OTP Guide: Route create command to appropriate node

- getting-started/mix-otp/task-and-gen-tcp.markdown
616d78c changed the example to use a default port if none was provided.
be1471b updated another code block to match that change.
This change fixes the remaining copy of that code.
Thus the trilogy of #1172 and #1367 is complete. :-)
> Fix inconsistency in task-and-gen-tcp.markdown

- getting-started/pattern-matching.markdown
Hello folks! For a beginner (like me), following the flow of the getting started documentation, at this point, he doesn't know how a map syntax looks like because this concept it's added later in the next sections, so might be confusing like it has been for me, that I was asking my self: what the heck is %{} ?
If this sounds reasonable please accept my PR. 
Thanks
> Clarified how to create a map

- getting-started/module-attributes.markdown
from the Docs: 
```
When registering an attribute, two options can be given:
:accumulate - several calls to the same attribute will accumulate instead of overriding the previous one. New attributes are always added to the top of the accumulated list.
```
> fixup example explanation

- _includes/search.html
With increasing privacy concerns regarding Google, we should seek to avoid them. This merge requests changes the documentation search field to use [searX](https://searx.me), a privacy-respecting metasearch engine.
The results are very close to that of Google, as I have configured this to use DuckDuckGo. This avoids sending data to Google.
If there are any issues, please contact me.
Many thanks.
> Change Google to DuckDuckGo

- getting-started/where-to-go-next.markdown
Proposition to mention/link to main page of short Erlang tutorial.
Cause there is no direct link from Concurrent Programming chapter page.
> Improve link to short Erlang tutorial

- getting-started/meta/macros.markdown
As they would result in warnings otherwise.
> macros.markdown: add `()` to nullary macros

- getting-started/introduction.markdown
It was left out by c6183c6daaf29b53b352e79792ca9207428d9976
> Remove numbered redirect

- getting-started/case-cond-and-if.markdown
The previous link pointed at the guard documentation for Elixir v1.9.4. This was moved from a separate "Guards" page in v1.9.4 to the "Patterns and Guards" page in v1.10.4.
> Update link to full guard documentation

- getting-started/structs.markdown
See the current: https://elixir-lang.org/getting-started/structs.html#default-values-and-required-keys
> add missing syntax highlighting to getting-started/structs.markdown

- getting-started/typespecs-and-behaviours.markdown
Following the issue raised in #1437, a small patch to add in the module name `Person` and the opening `do`
> Bug/Typo fix: Getting Started - Typespecs and Behaviours

- getting-started/mix-otp/distributed-tasks.markdown
Replaced "set" with "sent".
I'm also not sure if this is the best way to describe the situation? I think I'd rather call it output rather than input?
> knows all of the *output* should be *sent* back to the original node!
> Fix typo in distributed-tasks.markdown

- getting-started/binaries-strings-and-char-lists.markdown
I'm currently learning Elixir and noticed that the error message I got in 1.11.0 for this part is different than what was shown in the doc. I've updated it with the output I got, slightly modified to remove Elixir version number from output.
> Update error output message in binaries page

- _layouts/getting-started.html
I'm learning elixir now, but I feel lost when looking at the guides because the links looks all the same. So here I added a little control flow to disable the link of current page.
> Improve sidebar in the getting-started section (a little bit)

- getting-started/basic-operators.markdown
Because `&&` has `and` and `||` has `or`
> Getting started/Basic operators: Comment above `!` operator should be `not`

- getting-started/typespecs-and-behaviours.markdown
This PR adds a `@doc` tag along with the `@callback` tag. I think this might help to show where the doc usually is when using behaviours.
> Add example of @callback with @doc tag

- getting-started/modules-and-functions.markdown
Noticed that we can execute both `.ex` and `.exs` files with `elixir` command and no bytecode file will be created. Probably we need a note about that.
> fix(getting-started): add a note about scripting files execution

- getting-started/sigils.markdown
Issue
=====
When skimming the original phrasing of this sentence, I failed to understand the sentence properly. I read the sentence
> Sigils also support heredocs, that is, triple double- or single-quotes as separators
as
> Sigils also support heredocs, that is triple, double, or single quotes as separators
The difference between these two sentences is only punctuation. The good people of the Elixir Slack helped me to understand the true intent of the sentence.
Proposal
========
I believe this phrasing is somewhat clearer. While I am a native English speaker, I hope this rephrase is clearer to people who are not native English speakers. I'd be interested to get feedback from the community about this.
> Small phrasing change for Heredocs

- getting-started/mix-otp/ets.markdown
Separate the access controls so they each show up on their own line for easier readability
> Update ets.markdown for readability

- getting-started/mix-otp/dynamic-supervisor.markdown
`Supervisor` and `DynamicSupervisor` both have `count_children` and both appear to work identically in this situation. However, `KV.BucketSupervisor` is a `DynamicSupervisor` so we should probably use functions from the matching module.
While reading the docs I stumbled across this and had to go back up a bit to double-check it was still referring to the dynamic supervisor.
> Minor edit: use matching module to query dynamic supervisor

- getting-started/debugging.markdown
Found that current execution order fails in [Debugger section](https://elixir-lang.org/getting-started/debugging.html#debugger).
If I compile `example.ex` in IEx session I get this error:
```elixir
$ iex
iex(1)> c "example.ex"
[Example]
iex(2)> :debugger.start()
{:ok, #PID<0.115.0>}
iex(3)> :int.ni(Example)
** Invalid beam file or no abstract code: 'Elixir.Example'
:error
iex(4)> 
01:33:33.465 [error] [label: {:erl_prim_loader, :file_error}, report: 'File operation error: eisdir. Target: /Users/psylone/dev. Function: get_file. ']
```
But it works if I compile `example.ex` beforehand with `elixirc`. Moreover, if I do it and then invoke `c "example.ex"` inside an IEx session, I get this error again.
Tested with Elixir 1.11.3 on Ubuntu 20.04 LTS and macOS 10.14.6.
> fix(getting-started): change example.ex compilation order for debug

- index.html
This might be trying a little bit too hard but I though I'd send it anyway! :)
Before:
After:
> Highlight mix test output on the homepage

- install.markdown
From what I have seen, version managers are widely recommended in the
Elixir community, so it feels appropriate to add another reason to use
them.
> Add more reasons to use a version manager

- install.markdown
There was a person in the Elixir slack today that had trouble trying to
use a dependency that depended on xmerl. The solution for him was `sudo
dnf install erlang-xmerl` (although `sudo dnf install erlang` would have
been better).
I've also seen Fedora users having trouble running ElixirLS if they
don't have a full installation of erlang because they don't have the
`erlang-dialyzer` package:
https://github.com/elixir-lsp/elixir-ls/issues/231
Looking at the latest version of the elixir package for erlang we can
see that the "Requires" list is much smaller than the "BuildRequires"
list:
https://src.fedoraproject.org/rpms/elixir/blob/1118b2d2b1e973ba8188f7e479db174850697b2f/f/elixir.spec
Therefore, for typical Elixir development I believe it is important for
Fedora users to have a full …
> Recommend a full installation of erlang on Fedora

- _includes/top.html
- _layouts/blog.html
The feed url on the website is confusing, and do not work in many places. The original atom feed is good enough; there is no point to use the obsolete feedburner service.
> Nobody uses feedburner anymore. We should use the original feed

- getting-started/module-attributes.markdown
Updating module attributes section with note about how attributes defined with functions are processed at compile-time, not runtime.
> Update module attributes section

- getting-started/mix-otp/config-and-releases.markdown
1. Remove second "usually" word.
2. I think it's worth to note in guide that after we change `bar` release to use only `kv` app and add cookies to the both releases, we MUST reassemble `foo` one too. Otherwise cookies between nodes won't match, since we still have working release where `foo` uses autogenerated value.
> Remove `usually`

- getting-started/mix-otp/config-and-releases.markdown
In the Getting Started: Mix & OTP guide, the `cookie` changes in `foo`, but it does not instruct the learner to reassemble `foo`, so it results in an `Invalid challenge reply.`
> Getting Started: Reassemble after cookie change

- getting-started/mix-otp/distributed-tasks.markdown
To be able to use the `distributed` tag for the exclusion afaik we need the same config in `test_helper.exs` for `:kv_server` as we do for `:kv`. This instruction is implicit and I think it would be better to have it stated explicitly.
> Add missing piece of config info to instructions

- getting-started/mix-otp/distributed-tasks.markdown
I've noticed that output in my console was different than the one in the example when running `mix test`. The number of tests (8 instead of 7) might be my fault, although I tried to strictly follow the tutorial. However, I don't get the info about `on load` and `on tests` and my output says `excluded`, not `skipped`
Output of my `elixir -v`, ran on MacOSX (BigSur):
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
> Minor update on console output

- getting-started/sigils.markdown
Multi-character sigils are not supported (yet? 🙏  🙏 ), but the current doc is misleading. An "identifier" may usually have multiple characters.
> Clarify doc that custom sigils sigils accept a single letter only

- getting-started/try-catch-and-rescue.markdown
The `iex> what_happened` line is unnecessary. The `** (RuntimeError) undefined function: what_happened/0` will be caused by an attempt to access the variable within the `rescue` block. This line will attempt to do the same again, which will only demonstrate that the variables defined inside the `try` block do not leak, as was already shown by the preceding example.
> Update the example for variables visibility in the do-block of `try`

- getting-started/mix-otp/introduction-to-mix.markdown
I'm just getting into Elixir, so please bear with me if this is nonsense.
I was reading through the "introduction to Mix" guide, and https://github.com/elixir-lang/elixir-lang.github.com/blame/master/getting-started/mix-otp/introduction-to-mix.markdown#L283-L289 confused me slightly, since it is referencing that Mix.env is a function, but then not executing on the example usage.
By scrolling back, I could verify that the example mix.exs snippet https://github.com/elixir-lang/elixir-lang.github.com/blame/master/getting-started/mix-otp/introduction-to-mix.markdown#L85-L114, effectively points to executing Mix.env as function. 
Sorry if this comes across like a little bit nitpicky, just trying to contribute back my two cents, love the docs!
> Updates pseudocode example usage from Mix.env to Mix.env() to avoid confusion

- getting-started/mix-otp/config-and-releases.markdown
`Mix.env()` is not available in runtime.exs, and it's not clear from the text where the production routing table should go.  This clarifies that it should be in `runtime.exs` and demonstrates the use of `config_env()` (instead of `Mix.env()`)
Fixes #1535.
I'm not sure if overwriting the config is idiomatic, or if the default single entry routing table should be in a non-prod check?
> Production routing table config uses `config_env` (#1)

- getting-started/recursion.markdown
The previous implementation would print "Hello!" even if `n` was set to 0 or a negative number.
With this implementation, when 0 is passed, it will not print anything and when a negative number is passed we will get a `FunctionClauseError` which I believe is more appropriate.
I understand this is just meant for illustration purposes of how to perform "loops" in Elixir, but figured this doesn't complicate it much more and produces better results.
If this is seen as over-complicating the example, I'm happy to close the PR though :)
> Handle n = 0 for Recursion.print_multiple_times/2

- getting-started/mix-otp/ets.markdown
The output of the current version of ExUnit is different from here.
We need `assert` because this output should come from https://github.com/elixir-lang/elixir-lang.github.com/blob/01af1d9f2a14956371361ef55c663ed415e565bc/getting-started/mix-otp/genserver.markdown?plain=1#L245 .
> Update to the output of ExUnit 1.12

- _includes/important-links.html
The link on the page seems to be a dead one. I believe this is the the updated link https://cult.honeypot.io/originals/elixir-the-documentary
> Fix mini documentary link

- getting-started/binaries-strings-and-char-lists.markdown
The example now has a grapheme made of multiple code points. The "ł" example was removed, as it's not clear how to compose it out of 2 code points.
https://github.com/elixir-lang/elixir-lang.github.com/issues/1553
> Correct code point explanation

- getting-started/mix-otp/genserver.markdown
To prevent someone makes typo in `def handle_info({:DOWN, ref, :process, _pid, _reason}, {names, refs}) do`, such as `:proccess` for `:process`.
It might be difficult for a new programmer of elixir to find out why the bucket is not deleted properly.
> Add an log to avoid typo in another handle_info

- getting-started/structs.markdown
Info taken from: https://hexdocs.pm/elixir/Kernel.html#defstruct/1
Purpose of `@enforce_keys` was very vague and confusing earlier. Copy-pasted it here.
> Elaborate more on @enforce_keys

- docs.markdown
A path I'd like to fix points to a seemingly obsolete guides page. I'll fix it along with the path that is linked from "GUIDES" in the header menu.
> Fix the missing link to the guides page

- _posts/2021-05-19-elixir-v1-12-0-released.markdown
Hey!
First, it always feels good to see asciinema demo in new release posts ❤️ 
I've recently released a new major version of the asciinema web player which, among other things, comes with vastly better way of scaling the text with regards to the number of colums/rows and available space in the container element on the page (is also responsive, and looks much better on small screens, .e.g mobile). asciinema.org has been already updated to use it, including the embed script/iframe.
One result of this that's relevant for embedding is that font size is now automatically scaled to make all terminal content visible, while previously the font size was fixed and if there was more columns than can fit in the embed area the terminal content on the right side was cut off. 
For cases where you …
> Remove data-rows attr from asciinema script tags

- _includes/top.html
This will be more exposure to the DOCS section
Origated from:
https://elixirforum.com/t/onboarding-website-for-mix-build-tool/44740/5?u=eksperimental
Additionally we could remove "API Documentation" from the sidebard, (under important links)
Peronally I don't find it clear that about API. I think just "Documentation" will do a better job.
Screenshot:
> Add DOCS menu in top section

- getting-started/alias-require-and-import.markdown
Hi Elixir team,
While reading the [alias, require, and import docs](https://elixir-lang.org/getting-started/alias-require-and-import.html) and running Elixir 1.13.2, I got a slightly different output in an `iex` session when using the [Integer.is_odd/1](https://hexdocs.pm/elixir/1.12/Integer.html#is_odd/1) macro without calling `require` first.
This tinny PR aims to fix that by showing the most recent message from the error raised.
> Update macro usage error message when missing require

- getting-started/binaries-strings-and-char-lists.markdown
String.to_charlist on elixir returns the charlist of an string, which in
this case is [104, 233, 108, 108, 111], so i fixed this example by
putting the correct value
> fix: string example

- getting-started/mix-otp/dependencies-and-umbrella-projects.markdown
When I ran mix deps.get with a git repo as my dependency, it threw me the following error. Looks like git unauthenticated protocol is no longer supported for security reasons and https protocol is the way to go. 
mix deps.get
* Getting broadway_kafka (git://github.com/dashbitco/broadway_kafka.git)
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/
> git unauthenticated protocol is no longer supported

- install.markdown
Trying to install elixir on a Raspberry pi using the [official instructions](https://elixir-lang.org/install.html#raspberry-pi) leads to an error.
The `sudo apt-key add erlang_solutions.asc` command issues this message: 
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
```
It's just a warning, but things go wrong starting from that point...
It seems that this is the new way to import the key
```
cat erlang_solutions.asc | gpg --dearmor > erlang_solutions.gpg
sudo install -o root -g root -m 644 erlang_solutions.gpg /etc/apt/trusted.gpg.d/
```
And from that point on, it installs successfully.
> remove the "apt-key is deprecated" warning

- getting-started/mix-otp/task-and-gen-tcp.markdown
I think it would make sense to use port 4321 here since we are instructed to pass in `PORT=4321` to start the TCP acceptor. This would probably be most natural since the user wants to ensure that environment variables are working as indicated in the guide.
> Use port 4321 in telnet command (Task and gen_tcp guide)

- getting-started/mix-otp/introduction-to-mix.markdown
I'm new to Elixir and while reading the documentation about Mix there was a code snippet that got me thinking about the purpose of the flag `-S mix` when invoking `iex`. I went straight to run `iex --help` but the output from the help, assuming that's the right way to get it as a user, lacked documentation that flag.
I went ahead and added an additional phrase for people that might come across the same question. Please, let me know that's align how you'd expect this to be addressed or I should explore something else instead. For example improving the `iex --help` output. Thanks in advance for taking your time to review this tiny change.
> Add an additional note explaining what the '-S mix' flag is for

- getting-started/mix-otp/docs-tests-and-with.markdown
Updated "case" to "module" since `@moduletag :capture_log` refers to the whole module and not just a single test case.
> Update wording to make clear @moduletag is for the whole module

- getting-started/modules-and-functions.markdown
It might be convenient to immediately notify the readers of this guide that modules and functions must be capitalized correctly.
> Mention name casing rules for modules and functions

- getting-started/debugging.markdown
- getting-started/introduction.markdown
- getting-started/mix-otp/agent.markdown
- getting-started/mix-otp/supervisor-and-application.markdown
- getting-started/modules-and-functions.markdown
- getting-started/processes.markdown
Most of the corrections are just removing the line numbers from the `iex>` prompts to be consistent with the rest of the guide.
One is a trailing ) - `iex)>`
One is an empty trailing `iex>` prompt
> corrected inconsistent iex prompts

- getting-started/io-and-the-file-system.markdown
- getting-started/try-catch-and-rescue.markdown
```elixir
{:ok, file} = File.open("hello", [:write])
case File.read(file) do
{:ok, body}      -> # do something with the `body`
{:error, reason} -> # handle the error caused by `reason`
end
```
If this example is used verbatim, you will get the error 
```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
The following arguments were given to IO.chardata_to_string/1:
#PID<0.117.0>
Attempted function clauses (showing 2 out of 2):
def chardata_to_string(string) when is_binary(string)
def chardata_to_string(list) when is_list(list)
(elixir 1.13.4) lib/io.ex:627: IO.chardata_to_string/1
(elixir 1.13.4) lib/file.ex:341: File.read/1
```
`file` should be a path, not the PID set earlier in the guide
> File.read(file) receives a PID instead of a path

- install.markdown
chocolatey is rarely up to date and probably not even worth mentioning.  It probably does more harm than good having it here.
> add Scoop install instructions for Windows

- _data/elixir-versions.yml
- install.markdown
The [existing installation instructions](http://elixir-lang.org/install.html#precompiled-package) point to an incorrect location for the precompiled binary download. This PR adds a separate link for each supported OTP version:
I’ve added an `otp_versions` key to `_data/elixir-versions.yml`:
```yaml
v1_14:
name: v1.14
minimum_otp: 23.0
otp_versions: [23, 24, 25]
version: 1.14.0
docs_zip: true
```
Not sure whether this is the best approach, but hopefully it’s a good start.
> Link to correct precompiled binaries for supported OTP versions

- getting-started/alias-require-and-import.markdown
Updates the getting started guide for nested aliases to clarify `alias` behavior when applied to a module with multiple nesting e.g. `alias Foo.Bar.Baz`.
I think find this behavior very logical, but I was not certain what behavior Elixir provided without checking in `iex`.
> Add example with multiple nesting to `alias` guide

- getting-started/alias-require-and-import.markdown
This sentence was missing "use" despite its inclusion in the heading. The change includes the addition of code formatting to these words for clarification so it doesn't read as "... or use multiple modules".
If you'd prefer a roll-up of any changes I find in the getting started guide I can do so. It seems easier to accept/deny them separately though.
> Add `use` to sentence in multi-alias example

- install.markdown
Unfortunately the Erlang Solutions package repository for Ubuntu and Debian packages has not been updated for recent Ubuntu releases or the latest LTS release. Simplify the instructions to use `apt-get` by default, while still providing an option for those on older releases to use the Erlang Solutions packages.
Fixes #1575.
> Update Ubuntu/Debian install instructions

- crash-course.markdown
A friend of mine recently found this page, and when he asked me questions about it I saw that it was pretty outdated. I've gone and updated the formatting of at least all the Elixir code to match the modern formatter and idioms, but I'm not familiar enough with Erlang to know if those examples need updating or not.
Hope this helps, please let me know if I should change anything.
> Format and clean up crash-course

- js/index.js
When visiting elixir-lang.org I noticed that the there is no automatic redirect to https so I added a small script to perform such redirect when the http:// version of the page is loaded
> Redirect http traffic to https

- getting-started/typespecs-and-behaviours.markdown
Clarifies the statement "all types in Elixir are checked at runtime". They are not checked per say, exceptions are thrown. Thus I think it's better to say "Types are not checked at compile time".
Expands on what Types and Specs are useful for (i.e. documentation, code clarity, static code analysis).
> Improve 'Types and Specs' introduction

- getting-started/mix-otp/supervisor-and-application.markdown
Update output on child process crash to match the current Elixir version.
> Update the "Supervisor and Application" chapter

- _includes/important-links.html
It seems that the current link for "[Meetups around the world](http://elixir.meetup.com)" in `_includes/important-links.html` returns 404 with a blank page. 
A [cursory look at web.archive.org](https://web.archive.org/web/20181114232109/https://elixir.meetup.com/) suggests that it has acted as a 301 redirect to https://www.meetup.com/topics/elixir/. That 301 redirect doesn't seem to be in place any longer, hence the 404 we get today.
This PR changes the link to the one we were being directed to anyway.
> Fix link for meetups in sidebar

- _includes/important-links.html
- getting-started/introduction.markdown
Current [link](https://elixir-slackin.herokuapp.com/) points to a broken Heroku app.
Fixed in
- "Important links" sidebar
- "Asking questions" section on [Introduction](http://localhost:4000/getting-started/introduction.html#asking-questions) page
> Fix Slack community links

- getting-started/alias-require-and-import.markdown
Related: https://github.com/elixir-lang/elixir-lang.github.com/issues/1684
I re-read the first sentence of the section and noticed that macros are indeed mentioned (I must've not noticed it yesterday when I read it). Still, I think it could/should be made more explicit right at the beginning.
WDYT?
> Reorder `require` mention in `import` section

- index.html
I found this line that didn't flow well.
> Due to their lightweight nature, you can hundreds of thousands of processes concurrently in the same machine, using all machine resources efficiently (vertical scaling)
I added a _spawn_ after "you can"
> Due to their lightweight nature, you can _spawn_ hundreds of thousands
> Fixed some grammar on the Elixir landing page

- _includes/important-links.html
- install.markdown
It's not possible to join the Slack without being invited. Getting an invite currently means that you actually have to go to one of the other communities and then ask for an invite.
Examples of this:
- https://www.reddit.com/r/elixir/comments/129w7sf/how_to_join_elixir_slack/
- https://elixirforum.com/t/unable-to-join-the-slack-channel/56331
- https://www.reddit.com/r/elixir/comments/eawv49/cant_get_an_invitation_for_the_elixir_slack/
Pointing newcomers to ask questions in Slack is not great, since it sends them down a rabbit hole of trying to find out how to even get access to it.
> Remove links to Slack

- learning.markdown
The previous URL seems to have been overtaken by a spam site. We can
link to the GitHub repository instead which has a README that can guide
people through how to get started.
> Update URL for link to Elixir Koans

- getting-started/mix-otp/dynamic-supervisor.markdown
With Elixir version 1.15, to use `:observer.start()` in combination with iex, it is necessary to manually add the needed dependencies.
The needed dependencies are already mentioned in the "getting started" guide. This PR copies the note from there to the "mix guide" as requested in [an issue](https://github.com/elixir-lang/elixir-lang.github.com/issues/1712#issue-1848760461).
The same PR is opened in the repository `elixir-lang/elixir` (https://github.com/elixir-lang/elixir/pull/12861).
> Harmonize note about needed dependencies for observer.

- install.markdown
Without erlang-dev and erlang-xmerl, it's not possible to build mint, nor phoenix.
It seems reasonable to add these as general dependencies for everybody.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
$ mix hex.info
Hex:    2.0.6
Elixir: 1.15.7
OTP:    26.1.2
Built with: Elixir 1.14.2 and OTP 23.3
```
```
> Compiling 1 file (.erl)
src/mint_shims.erl:37:14: can't find include lib "public_key/include/public_key.hrl"
%   37| -include_lib("public_key/include/public_key.hrl").
```
> minor improvements to Debian/Ubuntu based install guide

- _posts/2023-12-22-elixir-v1-16-0-released.markdown
The link in the release blog post was broken, fixed with the current right one - whose name is macro not meta :)
Thanks for the 1.16 release and happy holidays!
> Fix meta programming anti-patterns link

- _includes/important-links.html
- install.markdown
This restores links to the Elixir Slack using a new [elixir-slack.community](https://elixir-slack.community) domain and [invite-driven plug app](https://github.com/sorentwo/elixir-slack).
> Add support links for elixir-slack.community

- install.markdown
On Debian bookworm the package erlang-dev needs to be installed as well, otherwise you will have problems creating the first elixir application (see https://github.com/elixir-lang/elixir/issues/12681#issuecomment-1699374362 )
> Expand install instructions for Debian

- learning.markdown
Hi all. 
Honestly nothing to add except what you can find in the title. I just noticed some links were broken and fixed them. Probably Pragprog has changed the url of its books.
> Fixing broken links in Learning (mostly Pragprog)

- install.markdown
Those using Fedora can get access to more recent releases, often bleeding edge, using Fedora's package manager.
Also note that documentation comes in a separate package, and can be useful for offline access.
> Document installing recent releases from Fedora Rawhide

- _data/elixir-versions.yml
- install.bat
- install.markdown
- install.sh
Ref: https://groups.google.com/g/elixir-lang-core/c/J-qZonSYNLE
> Add elixir-lang.org/install.sh and install.bat

- install.sh
This script uses `set -e` to immediately exit the program if any commands return non-zero, but `wait` without arguments does not reliably return with the exit code of a failed subprocess. (Exactly which exit code is returned depends, I believe, on the order in which the subprocesses exit.)
By waiting on both pids explicitly, we ensure that the script exits if either OTP or Elixir fails to install. In the case of #1781, this change makes it so that the script halts after the `curl` fails to download OTP master instead of carrying on as if nothing failed.
> Ensure install.sh exits if either of OTP or Elixir fails to install

- install.markdown
> fix: typo on install page

- index.html
This was a minor typo fix and therefore I didn't test the change by re-building the docs. If I've missed something, please let me know and I can take a closer look.
> Fix minor typo in index.html

- install.markdown
From the dnf docs:
`--repo=<repoid>, --repoid=<repoid>`
Enable just specific repositories by an id or a glob. Can be used multiple times with accumulative effect. It is basically a shortcut for `--disablerepo="*" --enablerepo=<repoid>` and is mutually exclusive with the `--disablerepo` option.
> Shorten Fedora dnf install command

- _posts/2025-02-26-elixir-openchain-certification.markdown
> Add OpenChain Announcement

- _posts/2020-10-08-real-time-communication-at-scale-with-elixir-at-discord.markdown
- _posts/2020-10-27-delivering-social-change-with-elixir-at-change.org.markdown
- _posts/2025-01-21-remote-elixir-case.markdown
- cases.html
- Add flagship boolean which will pin a case to the top of cases
- Sort all cases (including flagships) by date, most recent first
- Added suggested cases: Discord, Change.org and Remote
> Improve sorting of cases

- install.bat
- Added a PowerShell conditional check to see if `Expand-Archive` is available.
- If not, it falls back to using `.NET` APIs for zip extraction.
- Compatible with both PowerShell 5.1 and PowerShell 7+.
[Related issue](https://github.com/elixir-lang/elixir/issues/14321)
> Improve install.bat to support PowerShell 7

- learning.markdown
Fixes three things:
- Exercism is normally refered to as Exercism (not Exercism.org or Exercism.io). 
- The site moved from .io to .org a number of years back. 
- The icon URL was an old outdated one which is no longer loading.
> Fix Exercism icon and links
